import {opt_be_zeco,opt_be_zvat, opt_pl,opt_Currency,opt_Salesoffice, opt_it_zmot } from "./Opt_library";
import FormInput from "../components/form/FormInput";
import FormSelect from "../components/form/FormSelect";
import FormSelectSmall from "../components/form/FormSelectSmall";
 // ZECO/VAT fields map
 export const vatFields = [
    { name: "soldto_bezeco", label: "BE ZECO", options: opt_be_zeco },
    { name: "soldto_bezvat", label: "BE ZVAT", options: opt_be_zvat },
    { name: "soldto_dkzeco", label: "DK ZECO", options: opt_be_zeco },
    { name: "soldto_dkzvat", label: "DK ZVAT", options: opt_be_zvat },
    { name: "soldto_fizeco", label: "FI ZECO", options: opt_be_zeco },
    { name: "soldto_fizvat", label: "FI ZVAT", options: opt_be_zvat },
    { name: "soldto_frzeco", label: "FR ZECO", options: opt_be_zeco },
    { name: "soldto_frzvat", label: "FR ZVAT", options: opt_be_zvat },
    { name: "soldto_gbzvat", label: "GB ZVAT", options: opt_be_zvat },
    { name: "soldto_iezvat", label: "IE ZVAT", options: opt_be_zvat },
    { name: "soldto_itzcou", label: "IT ZCOU", options: opt_it_zmot },
    { name: "soldto_itzmot", label: "IT ZMOT", options: opt_it_zmot },
    { name: "soldto_itzvat", label: "IT ZVAT", options: opt_be_zvat },
    { name: "soldto_nlzvat", label: "NL ZVAT", options: opt_be_zvat },
    { name: "soldto_nozvat", label: "NO ZVAT", options: opt_be_zvat },
    { name: "soldto_nozeco", label: "NO ZECO", options: opt_be_zeco },
    { name: "soldto_sezvat", label: "SE ZVAT", options: opt_be_zvat },
    { name: "soldto_trzvat", label: "TR ZVAT", options: opt_be_zvat },
  ];
  // Map ZECO/VAT fields for ShipTo dynamically
 export const shiptoVatFields = [
    { name: "shipto_bezeco", label: "BE ZECO", options: opt_be_zeco,width:200 },
    { name: "shipto_bezvat", label: "BE ZVAT", options: opt_be_zvat },
    { name: "shipto_dkzeco", label: "DK ZECO", options: opt_be_zeco },
    { name: "shipto_dkzvat", label: "DK ZVAT", options: opt_be_zvat },
    { name: "shipto_fizeco", label: "FI ZECO", options: opt_be_zeco },
    { name: "shipto_fizvat", label: "FI ZVAT", options: opt_be_zvat },
    { name: "shipto_frzeco", label: "FR ZECO", options: opt_be_zeco },
    { name: "shipto_frzvat", label: "FR ZVAT", options: opt_be_zvat },
    { name: "shipto_gbzvat", label: "GB ZVAT", options: opt_be_zvat },
    { name: "shipto_iezvat", label: "IE ZVAT", options: opt_be_zvat },
    { name: "shipto_itzcou", label: "IT ZCOU", options: opt_it_zmot },
    { name: "shipto_itzmot", label: "IT ZMOT", options: opt_it_zmot },
    { name: "shipto_itzvat", label: "IT ZVAT", options: opt_be_zvat },
    { name: "shipto_nlzvat", label: "NL ZVAT", options: opt_be_zvat },
    { name: "shipto_nozvat", label: "NO ZVAT", options: opt_be_zvat },
    { name: "shipto_nozeco", label: "NO ZECO", options: opt_be_zeco },
    { name: "shipto_sezvat", label: "SE ZVAT", options: opt_be_zvat },
    { name: "shipto_trzvat", label: "TR ZVAT", options: opt_be_zvat },
  ];

    // Map PAYER fields dynamically
 export const payerFields = [
      { name: "payerno", label: "PAYER No.", width: 260 },
      { name: "payer_name", label: "Name", width: 330 },
      { name: "payerto_careoff", label: "C/O", width: 330 },
      { name: "payerto_streetno", label: "Street/House No", width: 260 },
      { name: "payerto_street2", label: "Street 2", width: 330 },
      { name: "payerto_street3", label: "Street 3", width: 330 },
      { name: "payerto_city", label: "City", width: 260 },
      { name: "payerto_postcode", label: "Postal Code", width: 200 },
      { name: "payerto_country", label: "Country", width: 180 },
      { name: "payerto_disctrict", label: "District (UK County)", width: 200 },
      { name: "payment_term", label: "Payment Terms", width: 260 },
      { name: "acc_assgmt_group", label: "Acct Assgmt Group", width: 330 },
      { name: "payment_method", label: "Payment Method", width: 330 },
    ];
    // Checkbox options for Pricing
    export const pricingCheckboxes = [
      { name: "a560", label: "Sales org./Distr. Chl/Division/Price list/Pr ref Material", code: "A560" },
      { name: "a513", label: "Sales org./Distr. Chl/Division/Sold-to pt/Pr ref Material", code: "A513" },
      { name: "a520", label: "Sales org/Distr Chl/Division/Sold-to/Ship-to/Pr ref Material", code: "A520" },
      { name: "a513_duplicate", label: "Sales org./Distr. Chl/Division/Sold-to pt/Pr ref Material", code: "A513" },
      { name: "a626", label: "Sales org./Distr. Chl/Division/Customer Hierarchy/Material", code: "A626" },
    ];
    // Map BILL TO fields for consistency
    export const billToFields = [
      { name: "billtono", label: "BILL TO No.", width: 260 },
      { name: "bill_name", label: "Name", width: 350 },
      { name: "billto_careoff", label: "C/O", width: 350 },
      { name: "billto_streetno", label: "Street/House No", width: 260 },
      { name: "billto_street2", label: "Street 2", width: 350 },
      { name: "billto_street3", label: "Street 3", width: 350 },
      { name: "billto_city", label: "City", width: 260 },
      { name: "billto_postcode", label: "Postal Code", width: 200 },
    ];
    // Map fields for Sales Area (example)
    export const salesAreaFields = [
      { name: "sales_office", label: "Sales Office", component: FormSelectSmall, options: opt_Salesoffice,width:330 },
      { name: "currency", label: "Currency", component: FormSelectSmall, options: opt_Currency,width:200, },
      { name: "price_group", label: "Price Group", component: FormInput },
      { name: "price_list", label: "Price List", component: FormSelectSmall, options: opt_pl,width:200 },
    ];
    // Map columns for Energy form
    export const Energy_columns = [

      { field: "companyID", headerName: "Company ID" },
      { field: "casetype", headerName: "Case Type" },
      { field: "cust_name", headerName: "Customer Name" },
      { field: "asset_name", headerName: "Asset Name" },
      { field: "companyAssetID", headerName: "Asset ID" },
      { field: "typeofrequest", headerName: "Type Of Request" },
      { field: "erp_system", headerName: "ERP System" },
      { field: "billtono", headerName: "Bill To No" },
      { field: "business", headerName: "Business" },
      { field: "contract_status", headerName: "Contract Status" },
      { field: "contracted_date", headerName: "Contracted Date" },
      { field: "currency", headerName: "Currency" },
      { field: "customer_group", headerName: "Customer Group" },
      { field: "division", headerName: "Division" },
      { field: "doc_num", headerName: "Document Number" },
      { field: "effective_date", headerName: "Effective Date" },
      { field: "file_name", headerName: "File Name" },
      { field: "frequency", headerName: "Frequency" },
      { field: "requsted_by", headerName: "Requested By" },
      { field: "sales_org", headerName: "Sales Organization" },
      { field: "soldtono", headerName: "Sold To No" },
      { field: "towncity", headerName: "Town / City" },
      { field: "tse_owner", headerName: "TSE Owner" },
     ];
     // Map columns for Marine form
  export const Marine_columns = [
    { field: "companyID", headerName: "Company ID" },
    { field: "cust_name", headerName: "Customer Name" },
    { field: "cabmnmc_soldtoid", headerName: "Sold To Id" },
    { field: "erp_system", headerName: "ERP System" },
    { field: "vessel_name", headerName: "Vessel Name" },
    { field: "vessel_sap_id", headerName: "Vessel SAP ID" },
    { field: "imo_number", headerName: "IMO Number" },
    { field: "tse_owner", headerName: "TSE Owner" },
    { field: "contract_status", headerName: "Contract Status" },
    { field: "contracted_date", headerName: "Contracted Date" },
    { field: "gmE_Region", headerName: "GME Region" },
    { field: "gmE_Country", headerName: "GME Country" },
    { field: "sales_Region", headerName: "Sales Region" },
    { field: "sales_Country", headerName: "Sales Country" },
    { field: "currency", headerName: "Currency" },
    { field: "business", headerName: "Business" },
    { field: "invoicing_Type", headerName: "Invoicing Type" },
    { field: "offer_at_vessel_level", headerName: "Offer At Vessel Level" },
    { field: "Frequency", headerName: "Frequency" },
    { field: "offer_band", headerName: "Offer Band" },
    { field: "foc", headerName: "FOC" },
    { field: "price", headerName: "Price" }
  ];

  export const opt_country_with_soldtoRegion=[
    { label: "AD - Andorra || Region : Europe and Africa", value: "AD - Andorra || Region : Europe and Africa" },
    { label: "AL - Albania || Region : Europe and Africa", value: "AL - Albania || Region : Europe and Africa" },
    { label: "AM - Armenia || Region : Europe and Africa", value: "AM - Armenia || Region : Europe and Africa" },
    { label: "AN - Dutch Antilles || Region : Europe and Africa", value: "AN - Dutch Antilles || Region : Europe and Africa" },
    { label: "AT - Austria || Region : Europe and Africa", value: "AT - Austria || Region : Europe and Africa" },
    { label: "AX - Aland Islands || Region : Europe and Africa", value: "AX - Aland Islands || Region : Europe and Africa" },
    { label: "AZ - Azerbaijan || Region : Europe and Africa", value: "AZ - Azerbaijan || Region : Europe and Africa" },
    { label: "BA - Bosnia-Herz. || Region : Europe and Africa", value: "BA - Bosnia-Herz. || Region : Europe and Africa" },
    { label: "BE - Belgium || Region : Europe and Africa", value: "BE - Belgium || Region : Europe and Africa" },
    { label: "BG - Bulgaria || Region : Europe and Africa", value: "BG - Bulgaria || Region : Europe and Africa" },
    { label: "BY - Belarus || Region : Europe and Africa", value: "BY - Belarus || Region : Europe and Africa" },
    { label: "CH - Switzerland || Region : Europe and Africa", value: "CH - Switzerland || Region : Europe and Africa" },
    { label: "CT - Turkish Cyprus || Region : Europe and Africa", value: "CT - Turkish Cyprus || Region : Europe and Africa" },
    { label: "CY - Cyprus || Region : Europe and Africa", value: "CY - Cyprus || Region : Europe and Africa" },
    { label: "CZ - Czech Republic || Region : Europe and Africa", value: "CZ - Czech Republic || Region : Europe and Africa" },
    { label: "DE - Germany || Region : Europe and Africa", value: "DE - Germany || Region : Europe and Africa" },
    { label: "DK - Denmark || Region : Europe and Africa", value: "DK - Denmark || Region : Europe and Africa" },
    { label: "EE - Estonia || Region : Europe and Africa", value: "EE - Estonia || Region : Europe and Africa" },
    { label: "ES - Spain || Region : Europe and Africa", value: "ES - Spain || Region : Europe and Africa" },
    { label: "EU - Europe || Region : Europe and Africa", value: "EU - Europe || Region : Europe and Africa" },
    { label: "FI - Finland || Region : Europe and Africa", value: "FI - Finland || Region : Europe and Africa" },
    { label: "FO - Faroe Islands || Region : Europe and Africa", value: "FO - Faroe Islands || Region : Europe and Africa" },
    { label: "FR - France || Region : Europe and Africa", value: "FR - France || Region : Europe and Africa" },
    { label: "GB - United Kingdom || Region : Europe and Africa", value: "GB - United Kingdom || Region : Europe and Africa" },
    { label: "GE - Georgia || Region : Europe and Africa", value: "GE - Georgia || Region : Europe and Africa" },
    { label: "GG - Guernsey || Region : Europe and Africa", value: "GG - Guernsey || Region : Europe and Africa" },
    { label: "GI - Gibraltar || Region : Europe and Africa", value: "GI - Gibraltar || Region : Europe and Africa" },
    { label: "GR - Greece || Region : Europe and Africa", value: "GR - Greece || Region : Europe and Africa" },
    { label: "HR - Croatia || Region : Europe and Africa", value: "HR - Croatia || Region : Europe and Africa" },
    { label: "HU - Hungary || Region : Europe and Africa", value: "HU - Hungary || Region : Europe and Africa" },
    { label: "IE - Ireland || Region : Europe and Africa", value: "IE - Ireland || Region : Europe and Africa" },
    { label: "IM - Isle of Man || Region : Europe and Africa", value: "IM - Isle of Man || Region : Europe and Africa" },
    { label: "IS - Iceland || Region : Europe and Africa", value: "IS - Iceland || Region : Europe and Africa" },
    { label: "IT - Italy || Region : Europe and Africa", value: "IT - Italy || Region : Europe and Africa" },
    { label: "JE - Jersey || Region : Europe and Africa", value: "JE - Jersey || Region : Europe and Africa" },
    { label: "LI - Liechtenstein || Region : Europe and Africa", value: "LI - Liechtenstein || Region : Europe and Africa" },
    { label: "LT - Lithuania || Region : Europe and Africa", value: "LT - Lithuania || Region : Europe and Africa" },
    { label: "LU - Luxembourg || Region : Europe and Africa", value: "LU - Luxembourg || Region : Europe and Africa" },
    { label: "LV - Latvia || Region : Europe and Africa", value: "LV - Latvia || Region : Europe and Africa" },
    { label: "MC - Monaco || Region : Europe and Africa", value: "MC - Monaco || Region : Europe and Africa" },
    { label: "MD - Moldova || Region : Europe and Africa", value: "MD - Moldova || Region : Europe and Africa" },
    { label: "ME - Montenegro || Region : Europe and Africa", value: "ME - Montenegro || Region : Europe and Africa" },
    { label: "MK - Macedonia || Region : Europe and Africa", value: "MK - Macedonia || Region : Europe and Africa" },
    { label: "MT - Malta || Region : Europe and Africa", value: "MT - Malta || Region : Europe and Africa" },
    { label: "NL - Netherlands || Region : Europe and Africa", value: "NL - Netherlands || Region : Europe and Africa" },
    { label: "NO - Norway || Region : Europe and Africa", value: "NO - Norway || Region : Europe and Africa" },
    { label: "PL - Poland || Region : Europe and Africa", value: "PL - Poland || Region : Europe and Africa" },
    { label: "PT - Portugal || Region : Europe and Africa", value: "PT - Portugal || Region : Europe and Africa" },
    { label: "RO - Romania || Region : Europe and Africa", value: "RO - Romania || Region : Europe and Africa" },
    { label: "RS - Serbia || Region : Europe and Africa", value: "RS - Serbia || Region : Europe and Africa" },
    { label: "RU - Russian Fed. || Region : Europe and Africa", value: "RU - Russian Fed. || Region : Europe and Africa" },
    { label: "R1 - Russia ROE || Region : Europe and Africa", value: "R1 - Russia ROE || Region : Europe and Africa" },
    { label: "SE - Sweden || Region : Europe and Africa", value: "SE - Sweden || Region : Europe and Africa" },
    { label: "SI - Slovenia || Region : Europe and Africa", value: "SI - Slovenia || Region : Europe and Africa" },
    { label: "SJ - Svalbard || Region : Europe and Africa", value: "SJ - Svalbard || Region : Europe and Africa" },
    { label: "SK - Slovakia || Region : Europe and Africa", value: "SK - Slovakia || Region : Europe and Africa" },
    { label: "SM - San Marino || Region : Europe and Africa", value: "SM - San Marino || Region : Europe and Africa" },
    { label: "UA - Ukraine || Region : Europe and Africa", value: "UA - Ukraine || Region : Europe and Africa" },
    { label: "VA - Vatican City || Region : Europe and Africa", value: "VA - Vatican City || Region : Europe and Africa" },
    { label: "XK - Kosovo || Region : Europe and Africa", value: "XK - Kosovo || Region : Europe and Africa" },
    { label: "XV - Northern Cyprus || Region : Europe and Africa", value: "XV - Northern Cyprus || Region : Europe and Africa" },
    { label: "YU - Yugoslavia || Region : Europe and Africa", value: "YU - Yugoslavia || Region : Europe and Africa" },
    { label: "AO - Angola || Region : Europe and Africa", value: "AO - Angola || Region : Europe and Africa" },
    { label: "BF - Burkina Faso || Region : Europe and Africa", value: "BF - Burkina Faso || Region : Europe and Africa" },
    { label: "BI - Burundi || Region : Europe and Africa", value: "BI - Burundi || Region : Europe and Africa" },
    { label: "BJ - Benin || Region : Europe and Africa", value: "BJ - Benin || Region : Europe and Africa" },
    { label: "BW - Botswana || Region : Europe and Africa", value: "BW - Botswana || Region : Europe and Africa" },
    { label: "CD - Congo DRC || Region : Europe and Africa", value: "CD - Congo DRC || Region : Europe and Africa" },
    { label: "CF - Central African Republic || Region : Europe and Africa", value: "CF - Central African Republic || Region : Europe and Africa" },
    { label: "CG - Congo || Region : Europe and Africa", value: "CG - Congo || Region : Europe and Africa" },
    { label: "CI - Cote D Ivoire || Region : Europe and Africa", value: "CI - Cote D Ivoire || Region : Europe and Africa" },
    { label: "CM - Cameroon || Region : Europe and Africa", value: "CM - Cameroon || Region : Europe and Africa" },
    { label: "CV - Cape Verde || Region : Europe and Africa", value: "CV - Cape Verde || Region : Europe and Africa" },
    { label: "DJ - Djibouti || Region : Europe and Africa", value: "DJ - Djibouti || Region : Europe and Africa" },
    { label: "DZ - Algeria || Region : Europe and Africa", value: "DZ - Algeria || Region : Europe and Africa" },
    { label: "EG - Egypt || Region : Europe and Africa", value: "EG - Egypt || Region : Europe and Africa" },
    { label: "EH - Western Sahara || Region : Europe and Africa", value: "EH - Western Sahara || Region : Europe and Africa" },
    { label: "ER - Eritrea || Region : Europe and Africa", value: "ER - Eritrea || Region : Europe and Africa" },
    { label: "ET - Ethiopia || Region : Europe and Africa", value: "ET - Ethiopia || Region : Europe and Africa" },
    { label: "GA - Gabon || Region : Europe and Africa", value: "GA - Gabon || Region : Europe and Africa" },
    { label: "GH - Ghana || Region : Europe and Africa", value: "GH - Ghana || Region : Europe and Africa" },
    { label: "GM - Gambia || Region : Europe and Africa", value: "GM - Gambia || Region : Europe and Africa" },
    { label: "GN - Guinea || Region : Europe and Africa", value: "GN - Guinea || Region : Europe and Africa" },
    { label: "GQ - Equatorial Guinea || Region : Europe and Africa", value: "GQ - Equatorial Guinea || Region : Europe and Africa" },
    { label: "GW - Guinea-Bissau || Region : Europe and Africa", value: "GW - Guinea-Bissau || Region : Europe and Africa" },
    { label: "KE - Kenya || Region : Europe and Africa", value: "KE - Kenya || Region : Europe and Africa" },
    { label: "KM - Comoros || Region : Europe and Africa", value: "KM - Comoros || Region : Europe and Africa" },
    { label: "LR - Liberia || Region : Europe and Africa", value: "LR - Liberia || Region : Europe and Africa" },
    { label: "LS - Lesotho || Region : Europe and Africa", value: "LS - Lesotho || Region : Europe and Africa" },
    { label: "LY - Libya || Region : Europe and Africa", value: "LY - Libya || Region : Europe and Africa" },
    { label: "MA - Morocco || Region : Europe and Africa", value: "MA - Morocco || Region : Europe and Africa" },
    { label: "MG - Madagascar || Region : Europe and Africa", value: "MG - Madagascar || Region : Europe and Africa" },
    { label: "ML - Mali || Region : Europe and Africa", value: "ML - Mali || Region : Europe and Africa" },
    { label: "MR - Mauritania || Region : Europe and Africa", value: "MR - Mauritania || Region : Europe and Africa" },
    { label: "MU - Mauritius || Region : Europe and Africa", value: "MU - Mauritius || Region : Europe and Africa" },
    { label: "MW - Malawi || Region : Europe and Africa", value: "MW - Malawi || Region : Europe and Africa" },
    { label: "MZ - Mozambique || Region : Europe and Africa", value: "MZ - Mozambique || Region : Europe and Africa" },
    { label: "NA - Namibia || Region : Europe and Africa", value: "NA - Namibia || Region : Europe and Africa" },
    { label: "NE - Niger || Region : Europe and Africa", value: "NE - Niger || Region : Europe and Africa" },
    { label: "NG - Nigeria || Region : Europe and Africa", value: "NG - Nigeria || Region : Europe and Africa" },
    { label: "OA - Other Africa || Region : Europe and Africa", value: "OA - Other Africa || Region : Europe and Africa" },
    { label: "RE - Reunion || Region : Europe and Africa", value: "RE - Reunion || Region : Europe and Africa" },
    { label: "RW - Rwanda || Region : Europe and Africa", value: "RW - Rwanda || Region : Europe and Africa" },
    { label: "SC - Seychelles || Region : Europe and Africa", value: "SC - Seychelles || Region : Europe and Africa" },
    { label: "SD - Sudan || Region : Europe and Africa", value: "SD - Sudan || Region : Europe and Africa" },
    { label: "SL - Sierra Leone || Region : Europe and Africa", value: "SL - Sierra Leone || Region : Europe and Africa" },
    { label: "SN - Senegal || Region : Europe and Africa", value: "SN - Senegal || Region : Europe and Africa" },
    { label: "SO - Somalia || Region : Europe and Africa", value: "SO - Somalia || Region : Europe and Africa" },
    { label: "SS - South Sudan || Region : Europe and Africa", value: "SS - South Sudan || Region : Europe and Africa" },
    { label: "ST - Sao Tome & Principe || Region : Europe and Africa", value: "ST - Sao Tome & Principe || Region : Europe and Africa" },
    { label: "SZ - Eswatini || Region : Europe and Africa", value: "SZ - Eswatini || Region : Europe and Africa" },
    { label: "TD - Chad || Region : Europe and Africa", value: "TD - Chad || Region : Europe and Africa" },
    { label: "TG - Togo || Region : Europe and Africa", value: "TG - Togo || Region : Europe and Africa" },
    { label: "TN - Tunisia || Region : Europe and Africa", value: "TN - Tunisia || Region : Europe and Africa" },
    { label: "TZ - Tanzania || Region : Europe and Africa", value: "TZ - Tanzania || Region : Europe and Africa" },
    { label: "UG - Uganda || Region : Europe and Africa", value: "UG - Uganda || Region : Europe and Africa" },
    { label: "YT - Mayotte || Region : Europe and Africa", value: "YT - Mayotte || Region : Europe and Africa" },
    { label: "ZA - South Africa || Region : Europe and Africa", value: "ZA - South Africa || Region : Europe and Africa" },
    { label: "ZM - Zambia || Region : Europe and Africa", value: "ZM - Zambia || Region : Europe and Africa" },
    { label: "ZW - Zimbabwe || Region : Europe and Africa", value: "ZW - Zimbabwe || Region : Europe and Africa" },
    { label: "AG - Antigua & Barbuda || Region : Americas", value: "AG - Antigua & Barbuda || Region : Americas" },
    { label: "AI - Anguilla || Region : Americas", value: "AI - Anguilla || Region : Americas" },
    { label: "AR - Argentina || Region : Americas", value: "AR - Argentina || Region : Americas" },
    { label: "AW - Aruba || Region : Americas", value: "AW - Aruba || Region : Americas" },
    { label: "BB - Barbados || Region : Americas", value: "BB - Barbados || Region : Americas" },
    { label: "BL - St Barthelemy || Region : Americas", value: "BL - St Barthelemy || Region : Americas" },
    { label: "BM - Bermuda || Region : Americas", value: "BM - Bermuda || Region : Americas" },
    { label: "BO - Bolivia || Region : Americas", value: "BO - Bolivia || Region : Americas" },
    { label: "BQ - Bonaire, Saba || Region : Americas", value: "BQ - Bonaire, Saba || Region : Americas" },
    { label: "BR - Brazil || Region : Americas", value: "BR - Brazil || Region : Americas" },
    { label: "BS - Bahamas || Region : Americas", value: "BS - Bahamas || Region : Americas" },
    { label: "BZ - Belize || Region : Americas", value: "BZ - Belize || Region : Americas" },
    { label: "CA - Canada || Region : Americas", value: "CA - Canada || Region : Americas" },
    { label: "CL - Chile || Region : Americas", value: "CL - Chile || Region : Americas" },
    { label: "CO - Colombia || Region : Americas", value: "CO - Colombia || Region : Americas" },
    { label: "CR - Costa Rica || Region : Americas", value: "CR - Costa Rica || Region : Americas" },
    { label: "CU - Cuba || Region : Americas", value: "CU - Cuba || Region : Americas" },
    { label: "CW - Curacao || Region : Americas", value: "CW - Curacao || Region : Americas" },
    { label: "DM - Dominica || Region : Americas", value: "DM - Dominica || Region : Americas" },
    { label: "DO - Dominican Republic || Region : Americas", value: "DO - Dominican Republic || Region : Americas" },
    { label: "EC - Ecuador || Region : Americas", value: "EC - Ecuador || Region : Americas" },
    { label: "FK - Falkland Islands || Region : Americas", value: "FK - Falkland Islands || Region : Americas" },
    { label: "GD - Grenada || Region : Americas", value: "GD - Grenada || Region : Americas" },
    { label: "GF - French Guiana || Region : Americas", value: "GF - French Guiana || Region : Americas" },
    { label: "GL - Greenland || Region : Americas", value: "GL - Greenland || Region : Americas" },
    { label: "GP - Guadeloupe || Region : Americas", value: "GP - Guadeloupe || Region : Americas" },
    { label: "GT - Guatemala || Region : Americas", value: "GT - Guatemala || Region : Americas" },
    { label: "GY - Guyana || Region : Americas", value: "GY - Guyana || Region : Americas" },
    { label: "HN - Honduras || Region : Americas", value: "HN - Honduras || Region : Americas" },
    { label: "HT - Haiti || Region : Americas", value: "HT - Haiti || Region : Americas" },
    { label: "JM - Jamaica || Region : Americas", value: "JM - Jamaica || Region : Americas" },
    { label: "KN - St Kitts & Nevis || Region : Americas", value: "KN - St Kitts & Nevis || Region : Americas" },
    { label: "KY - Cayman Islands || Region : Americas", value: "KY - Cayman Islands || Region : Americas" },
    { label: "LC - Saint Lucia || Region : Americas", value: "LC - Saint Lucia || Region : Americas" },
    { label: "MQ - Martinique || Region : Americas", value: "MQ - Martinique || Region : Americas" },
    { label: "MS - Montserrat || Region : Americas", value: "MS - Montserrat || Region : Americas" },
    { label: "MX - Mexico || Region : Americas", value: "MX - Mexico || Region : Americas" },
    { label: "NI - Nicaragua || Region : Americas", value: "NI - Nicaragua || Region : Americas" },
    { label: "PA - Panama || Region : Americas", value: "PA - Panama || Region : Americas" },
    { label: "PE - Peru || Region : Americas", value: "PE - Peru || Region : Americas" },
    { label: "PM - St Pierre & Miquelon || Region : Americas", value: "PM - St Pierre & Miquelon || Region : Americas" },
    { label: "PR - Puerto Rico || Region : Americas", value: "PR - Puerto Rico || Region : Americas" },
    { label: "PY - Paraguay || Region : Americas", value: "PY - Paraguay || Region : Americas" },
    { label: "SR - Suriname || Region : Americas", value: "SR - Suriname || Region : Americas" },
    { label: "SV - El Salvador || Region : Americas", value: "SV - El Salvador || Region : Americas" },
    { label: "TC - Turks & Caicos || Region : Americas", value: "TC - Turks & Caicos || Region : Americas" },
    { label: "TT - Trinidad & Tobago || Region : Americas", value: "TT - Trinidad & Tobago || Region : Americas" },
    { label: "US - United States || Region : Americas", value: "US - United States || Region : Americas" },
    { label: "UY - Uruguay || Region : Americas", value: "UY - Uruguay || Region : Americas" },
    { label: "VC - St Vincent || Region : Americas", value: "VC - St Vincent || Region : Americas" },
    { label: "VE - Venezuela || Region : Americas", value: "VE - Venezuela || Region : Americas" },
    { label: "VG - British Virgin Islands || Region : Americas", value: "VG - British Virgin Islands || Region : Americas" },
    { label: "VI - American Virgin Islands || Region : Americas", value: "VI - American Virgin Islands || Region : Americas" },
    { label: "AE - United Arab Emirates || Region : AsPac", value: "AE - United Arab Emirates || Region : AsPac" },
    { label: "AF - Afghanistan || Region : AsPac", value: "AF - Afghanistan || Region : AsPac" },
    { label: "AQ - Antarctica || Region : AsPac", value: "AQ - Antarctica || Region : AsPac" },
    { label: "AS - American Samoa || Region : AsPac", value: "AS - American Samoa || Region : AsPac" },
    { label: "AU - Australia || Region : AsPac", value: "AU - Australia || Region : AsPac" },
    { label: "BD - Bangladesh || Region : AsPac", value: "BD - Bangladesh || Region : AsPac" },
    { label: "BH - Bahrain || Region : AsPac", value: "BH - Bahrain || Region : AsPac" },
    { label: "BN - Brunei || Region : AsPac", value: "BN - Brunei || Region : AsPac" },
    { label: "BT - Bhutan || Region : AsPac", value: "BT - Bhutan || Region : AsPac" },
    { label: "BV - Bouvet Island || Region : AsPac", value: "BV - Bouvet Island || Region : AsPac" },
    { label: "CC - Cocos Islands || Region : AsPac", value: "CC - Cocos Islands || Region : AsPac" },
    { label: "CN - China || Region : AsPac", value: "CN - China || Region : AsPac" },
    { label: "CX - Christmas Island || Region : AsPac", value: "CX - Christmas Island || Region : AsPac" },
    { label: "FJ - Fiji || Region : AsPac", value: "FJ - Fiji || Region : AsPac" },
    { label: "FM - Micronesia || Region : AsPac", value: "FM - Micronesia || Region : AsPac" },
    { label: "GU - Guam || Region : AsPac", value: "GU - Guam || Region : AsPac" },
    { label: "HK - Hong Kong || Region : AsPac", value: "HK - Hong Kong || Region : AsPac" },
    { label: "HM - Heard & McDonald Islands || Region : AsPac", value: "HM - Heard & McDonald Islands || Region : AsPac" },
    { label: "ID - Indonesia || Region : AsPac", value: "ID - Indonesia || Region : AsPac" },
    { label: "IL - Israel || Region : AsPac", value: "IL - Israel || Region : AsPac" },
    { label: "IN - India || Region : AsPac", value: "IN - India || Region : AsPac" },
    { label: "IO - British Indian Ocean Territory || Region : AsPac", value: "IO - British Indian Ocean Territory || Region : AsPac" },
    { label: "IQ - Iraq || Region : AsPac", value: "IQ - Iraq || Region : AsPac" },
    { label: "IR - Iran || Region : AsPac", value: "IR - Iran || Region : AsPac" },
    { label: "JO - Jordan || Region : AsPac", value: "JO - Jordan || Region : AsPac" },
    { label: "JP - Japan || Region : AsPac", value: "JP - Japan || Region : AsPac" },
    { label: "KG - Kyrgyzstan || Region : AsPac", value: "KG - Kyrgyzstan || Region : AsPac" },
    { label: "KH - Cambodia || Region : AsPac", value: "KH - Cambodia || Region : AsPac" },
    { label: "KI - Kiribati || Region : AsPac", value: "KI - Kiribati || Region : AsPac" },
    { label: "KP - North Korea || Region : AsPac", value: "KP - North Korea || Region : AsPac" },
    { label: "KR - South Korea || Region : AsPac", value: "KR - South Korea || Region : AsPac" },
    { label: "KW - Kuwait || Region : AsPac", value: "KW - Kuwait || Region : AsPac" },
    { label: "KZ - Kazakhstan || Region : AsPac", value: "KZ - Kazakhstan || Region : AsPac" },
    { label: "LA - Laos || Region : AsPac", value: "LA - Laos || Region : AsPac" },
    { label: "LB - Lebanon || Region : AsPac", value: "LB - Lebanon || Region : AsPac" },
    { label: "LK - Sri Lanka || Region : AsPac", value: "LK - Sri Lanka || Region : AsPac" },
    { label: "LDB - Land Based || Region : AsPac", value: "LDB - Land Based || Region : AsPac" },
    { label: "MM - Myanmar || Region : AsPac", value: "MM - Myanmar || Region : AsPac" },
    { label: "MN - Mongolia || Region : AsPac", value: "MN - Mongolia || Region : AsPac" },
    { label: "MO - Macau || Region : AsPac", value: "MO - Macau || Region : AsPac" },
    { label: "MP - Northern Mariana Islands || Region : AsPac", value: "MP - Northern Mariana Islands || Region : AsPac" },
    { label: "MV - Maldives || Region : AsPac", value: "MV - Maldives || Region : AsPac" },
    { label: "MY - Malaysia || Region : AsPac", value: "MY - Malaysia || Region : AsPac" },
    { label: "NC - New Caledonia || Region : AsPac", value: "NC - New Caledonia || Region : AsPac" },
    { label: "NF - Norfolk Island || Region : AsPac", value: "NF - Norfolk Island || Region : AsPac" },
    { label: "NP - Nepal || Region : AsPac", value: "NP - Nepal || Region : AsPac" },
    { label: "NR - Nauru || Region : AsPac", value: "NR - Nauru || Region : AsPac" },
    { label: "NT - NATO || Region : AsPac", value: "NT - NATO || Region : AsPac" },
    { label: "NU - Niue || Region : AsPac", value: "NU - Niue || Region : AsPac" },
    { label: "NZ - New Zealand || Region : AsPac", value: "NZ - New Zealand || Region : AsPac" },
    { label: "OM - Oman || Region : AsPac", value: "OM - Oman || Region : AsPac" },
    { label: "OR - Orange || Region : AsPac", value: "OR - Orange || Region : AsPac" },
    { label: "PF - French Polynesia || Region : AsPac", value: "PF - French Polynesia || Region : AsPac" },
    { label: "PG - Papua New Guinea || Region : AsPac", value: "PG - Papua New Guinea || Region : AsPac" },
    { label: "PH - Philippines || Region : AsPac", value: "PH - Philippines || Region : AsPac" },
    { label: "PK - Pakistan || Region : AsPac", value: "PK - Pakistan || Region : AsPac" },
    { label: "PS - Palestine || Region : AsPac", value: "PS - Palestine || Region : AsPac" },
    { label: "PW - Palau || Region : AsPac", value: "PW - Palau || Region : AsPac" },
    { label: "QA - Qatar || Region : AsPac", value: "QA - Qatar || Region : AsPac" },
    { label: "SA - Saudi Arabia || Region : AsPac", value: "SA - Saudi Arabia || Region : AsPac" },
    { label: "SB - Solomon Islands || Region : AsPac", value: "SB - Solomon Islands || Region : AsPac" },
    { label: "SG - Singapore || Region : AsPac", value: "SG - Singapore || Region : AsPac" },
    { label: "SH - Saint Helena || Region : AsPac", value: "SH - Saint Helena || Region : AsPac" },
    { label: "SHP - SH Country || Region : AsPac", value: "SHP - SH Country || Region : AsPac" },
    { label: "SY - Syria || Region : AsPac", value: "SY - Syria || Region : AsPac" },
    { label: "T1 - Turkey ROW || Region : AsPac", value: "T1 - Turkey ROW || Region : AsPac" },
    { label: "TF - French Southern Territories || Region : AsPac", value: "TF - French Southern Territories || Region : AsPac" },
    { label: "TH - Thailand || Region : AsPac", value: "TH - Thailand || Region : AsPac" },
    { label: "TJ - Tajikistan || Region : AsPac", value: "TJ - Tajikistan || Region : AsPac" },
    { label: "TK - Tokelau || Region : AsPac", value: "TK - Tokelau || Region : AsPac" },
    { label: "TL - Timor-Leste || Region : AsPac", value: "TL - Timor-Leste || Region : AsPac" },
    { label: "TM - Turkmenistan || Region : AsPac", value: "TM - Turkmenistan || Region : AsPac" },
    { label: "TO - Tonga || Region : AsPac", value: "TO - Tonga || Region : AsPac" },
    { label: "TP - East Timor || Region : AsPac", value: "TP - East Timor || Region : AsPac" },
    { label: "TR - Turkey || Region : AsPac", value: "TR - Turkey || Region : AsPac" },
    { label: "TV - Tuvalu || Region : AsPac", value: "TV - Tuvalu || Region : AsPac" },
    { label: "TW - Taiwan || Region : AsPac", value: "TW - Taiwan || Region : AsPac" },
    { label: "UZ - Uzbekistan || Region : AsPac", value: "UZ - Uzbekistan || Region : AsPac" },
    { label: "VN - Vietnam || Region : AsPac", value: "VN - Vietnam || Region : AsPac" },
    { label: "VU - Vanuatu || Region : AsPac", value: "VU - Vanuatu || Region : AsPac" },
    { label: "WF - Wallis & Futuna || Region : AsPac", value: "WF - Wallis & Futuna || Region : AsPac" },
    { label: "WO - Rest of World || Region : AsPac", value: "WO - Rest of World || Region : AsPac" },
    { label: "WS - Samoa || Region : AsPac", value: "WS - Samoa || Region : AsPac" },
    { label: "YE - Yemen || Region : AsPac", value: "YE - Yemen || Region : AsPac" },
    { label: " || Region : ", value: " || Region : " },
  ]

  export const Marine_initialValues = {
    SelectedCustomerID:0,
    ownershipschangeeffectivedate: new Date().toISOString().split("T")[0],
    effective_date: new Date().toISOString().split("T")[0],
    effectivatedateratechange: new Date().toISOString().split("T")[0],
    detailsofrequest: "",
    tableData: [],
    companysearch: "",
    technicalemail: "",
    pricingpolicy: "",
    servicedescription: "Basic Sample",
    uoafocyear: "",
    uoachargeunit: "",
    Band: "",
    domestic:false,
    FOC: "",
    Price: "",
    uoaSamples: [
      {
        ID: "",
        sample_uoa: "",
        focyear_uoa: "",
        chargeunit_uoa: "",
      },
    ],
    sdaofferinclude: "",
    sdapricingpolicy: "",
    sdaservicedescription: "SDA basic (Fuel & System)",
    sdachargeunit: "",
    sdaFocType: "",
    sdaSamples: [
      {
        ID: "",
        sample_sda: "",
        focyear_sda: "",
        chargeunit_sda: "",
      },
    ],
    purou: "",
    requsted_by: "",
    approved_by: "",
    doc_num: "",
    casetype: "",
    amendmodifytechnicaloffer: "",
    offerfornewvessel: "",
    offerforexistingvessel: "",
    req_comments: "",
    marineerpsystemtype: "",
    salesaccounttype: "",
    salesaccountdescription_newaccount: "",
    salesaccountdescription_existingaccount: "",
    newaccountsetup: "",
    newvesselsetup: "",
    includeuoaoffer: "",
    typeofcustomer: "",
    approvedby_secondary: "",
    approvalattachments: "",
    netcasenumber: "",
    investmentapprovedby: "",
    setuptype: "",
    priority: "",
    soldto_city: "",
    custdetailschange: "",
    soldtoname: "",
    cabmnmc_soldtoid: "",
    registered_streetno: "",
    registered_street2: "",
    registered_street3: "",
    registered_city: "",
    registered_postcode: "",
    registered_country: "",
    custaccountname: "",
    custometaccountmnmc: "",
    invoicepointname: "",
    invoicepointmnmc: "",
    name1: "",
    name2: "",
    name3: "",
    name4: "",
    invoicepoint_streetno: "",
    invoicepoint_street2: "",
    invoicepoint_street3: "",
    invoicepoint_street4: "",
    invoicepoint_city: "",
    invoicepoint_postcode: "",
    invoicepoint_country: "",
    vatregno: "",
    extrainvoiceaddress: "",
    billtoparty: "",
    printerlocation: "",
    printername: "",
    pdfinvoceemail: "",
    faxnumber: "",
    directtocustomer: false,
    otherroute: "",
    originaldrn: "",
    taxcontractsignoff: "",
    regionalmanager: "",
    creditapprovalchange: "",
    approvedcreditlimit: 0,
    Creditapprovedby: "",
    creditapprovalnumber: "",
    paymentterm: "",
    daysfrom: 0,
    otherpaymentterm: "",
    Pricingdetailsapprovedby: "",
    pricelisttoapply: "",
    chargemodel: "",
    international: false,
    localinternationalvalue: "",
    rebatechange: "",
    rebaterequired: false,
    rebatedetails: "",
    investmentrequired: false,
    investmentdeatils: "",
    paymentmethod: "",
    creditreleasedate: new Date().toISOString().split("T")[0],
    Custaccountname: "",
    bankingname: "",
    banksortcode: "",
    beneficiary: "",
    bankaccntnumber: "",
    residencetownofbank: "",
    referencerequired: "",
    swiftcode: "",
    cabmnmc: "",
    custacctmnmc: "",
    documentpreparedby: "",
    rebateattachments: "",
    iciscustomer: false,
    icisrate: 0,
    remarks: "",
    localinternational: false,
    service_band_currency: "",
    uoainvoicingfrwequency: "",
    uoacurrency: "",
    prepaidsamlebottlepack: "",
    tsenameemail: "",
    accountname: "",
    CompanyID: "",
    CompanyAssetID: "",
    contract_status: "",
    contracted_date: "",
    currency: "",
    cust_name: "",
    data_source: "",
    Discount: "",
    erp_system: "",
    Frequency: "",
    GME_Country: "",
    GME_Region: "",
    imo_number: "",
    offer_at_vessel_level: "",
    offer_band: "",
    invoicing_Type: "",
    sales_Region: "",
    sales_Country: "",
    tse_owner: "",
    vessel_name: "",
    vessel_sap_id: "",
  };

  export const Energy_initialValues = {
    // CDD Clearance
    ownercompnyname:"",
    companysearch:"",
    PricingPolicy: "",
    SelectedCustomerID:0,
    energyERPcustType: "",
    energyERPsystem: "",
    cddcustname: "",
    rating: "",
    cddcopieddata: "",
    business: "",
    po_required: false,
    energyERPfrequency: "QUARTERLY",
    // Customer Master
    cust_name: "",
    requsted_by: "",
    approved_by: "",
    effective_date: new Date()
      .toISOString()
      .split("T")[0],
    doc_num: "",
    sales_org: "",
    dist_channel: "",
    division: "02 (Lubricants)",
    typeofrequest: "",
    energyERPaccounttype: "",
    erpnewaccounttype: "",
    tsenameemail: "",

    // Case Information
    casetype: "",
    amendmodifytechnicaloffer: "",
    offerfornewvessel: "",
    offerforexistingvessel: "",
    req_comments: "",

    // Sold To Address
    soldtono: "",
    legal_entity: "",
    soldto_careoff: "",
    soldto_streetno: "",
    soldto_street2: "",
    soldto_street3: "",
    soldto_city: "",
    soldto_postcode: "",
    soldto_country: "",
    soldto_telno: "",
    soldto_faxno: "",
    soldto_mobile: "",
    soldto_email: "",
    soldto_vat: "",
    soldto_Creditapproveno: "",
    soldto_bezeco: "",
    soldto_bezvat: "",
    soldto_dkzeco: "",
    soldto_dkzvat: "",
    soldto_fizeco: "",
    soldto_fizvat: "",
    soldto_frzeco: "",
    soldto_frzvat: "",
    soldto_gbzvat: "",
    soldto_iezvat: "",
    soldto_itzcou: "",
    soldto_itzmot: "",
    soldto_itzvat: "",
    soldto_nlzvat: "",
    soldto_nozvat: "",
    soldto_nozeco: "",
    soldto_sezvat: "",
    soldto_trzvat: "",

    // Ship To Address
    shiptono: "",
    shipto_legal_entity: "",
    shipto_careoff: "",
    shipto_streetno: "",
    shipto_street2: "",
    shipto_street3: "",
    shipto_city: "",
    shipto_postcode: "",
    shipto_country: "",
    transport_zone: "",
    language_key: "",
    shipto_district: "",
    shipto_bezeco: "",
    shipto_bezvat: "",
    shipto_dkzeco: "",
    shipto_dkzvat: "",
    shipto_fizeco: "",
    shipto_fizvat: "",
    shipto_frzeco: "",
    shipto_frzvat: "",
    shipto_gbzvat: "",
    shipto_iezvat: "",
    shipto_itzcou: "",
    shipto_itzmot: "",
    shipto_itzvat: "",
    shipto_nlzvat: "",
    shipto_nozvat: "",
    shipto_nozeco: "",
    shipto_sezvat: "",
    shipto_trzvat: "",

    // Bill To Address
    billtono: "",
    bill_name: "",
    billto_careoff: "",
    billto_streetno: "",
    billto_street2: "",
    billto_street3: "",
    billto_city: "",
    billto_postcode: "",
    billto_country: "",
    billto_district: "",
    billingemail: "",

    // Payer Address / Pricing Billing
    payerno: "",
    payer_name: "",
    payerto_careoff: "",
    payerto_streetno: "",
    payerto_street2: "",
    payerto_street3: "",
    payerto_city: "",
    payerto_postcode: "",
    payerto_country: "",
    payerto_disctrict: "",
    payment_term: "",
    acc_assgmt_group: "",
    payment_method: "",

    // Sales / Control / Shipping / Billing / Attributes / Pricing
    account_manager: "",
    key_account_manager: "",
    industry_key: "",
    sales_office: "",
    currency: "",
    price_group: "",
    price_list: "",
    shipping_conditions: "",
    delivering_plant: "",
    Delivery_priority: "",
    invoicing_dates: "",
    inco_terms: "",
    towncity: "",
    profile_centre_assignment: "",
    invoice_brand: "",
    sub_sector: "",
    customer_group: "",
    file_name: "",
    pricing_condition: "",
    a560: false,
    a513: false,
    a520: false,
    a513_duplicate: false,
    a626: false,
    tableData: [],
  };