import React from "react";

const groups = [
  "Group 1","Group 2","Group 3","Group 4","Group 5","Group 6","Group 7","Group 8","Group 9","Group 10","Group 11","Group 12","Group 13"
];

const subHeaders = [
  "$/HLS","$/HLS","$/HLS","$/HLS","$/HLS","$/HLS","$/HLS","$/HLS","$/HLS","$/HLS","$/HLS","$/HK","$/HLS"
];

const portRows = [
  { name: "Red Port", values: Array(13).fill("") },
  { name: "Green Port", values: ["","","","","10","","","","","","","",""] },
  { name: "White Port", values: Array(13).fill("") }
];
export const opt_sales_org = [
  { label: "NO10 / Norway", value: "NO10" },
  { label: "DK08 / Denmark", value: "DK08" },
  { label: "GB07 / UK", value: "GB07" },
  { label: "US9S / US NIKE", value: "US9S" },
  { label: "TR17 / Turkey", value: "TR17" }
];

export const opt_Shipping=[
    {label:"01-Road FTL Delivered", value:"01-Road FTL Delivered"},
    {label:"02-Part Truckload Delv", value:"02-Part Truckload Delv"},
    {label:"03-Pick up", value:"03-Pick up"},
    {label:"04-Ground/Parcel", value:"04-Ground/Parcel"},
    {label:"05-Marine Barge", value:"05-Marine Barge"},
    {label:"06-Marine Pick up", value:"06-Marine Pick up"},
    {label:"07-Inland Barge Delv", value:"07-Inland Barge Delv"},
    {label:"08-Inland Barge Pick up", value:"08-Inland Barge Pick up"},
    {label:"09-Pipeline", value:"09-Pipeline"},
    {label:"10-Rush", value:"10-Rush"},
    {label:"11-Inter Plant Transfer", value:"11-Inter Plant Transfer"},
    {label:"12-Rail Delivered", value:"12-Rail Delivered"},
    {label:"13-Rail Pick up", value:"13-Rail Pick up"},
    {label:"14-Air Freight", value:"14-Air Freight"},
    {label:"15-Special Reqmnts", value:"15-Special Reqmnts"},
    {label:"16-Multi Entregas", value:"16-Multi Entregas"},
    {label:"17-Multi-modal", value:"17-Multi-modal"},
    {label:"18-EXP.FM.FR.PORT", value:"18-EXP.FM.FR.PORT"},
    {label:"19-Marine Barge filling", value:"19-Marine Barge filling"},
    {label:"20-Returns", value:"20-Returns"},
    {label:"21-Drop Shipment", value:"21-Drop Shipment"},
    {label:"22-Delvd cust pays cost", value:"22-Delvd cust pays cost"},
    {label:"23-Delvd costs return", value:"23-Delvd costs return"},
    {label:"24-Inbound Delivery PRL", value:"24-Inbound Delivery PRL"},
    {label:"25-Ret -Cust Drop Off", value:"25-Ret -Cust Drop Off"},
    {label:"26-Marine Road", value:"26-Marine Road"},
    {label:"27-French Export Pck Up", value:"27-French Export Pck Up"},
    {label:"28-Parcel rates", value:"28-Parcel rates"},
    {label:"29-Parcel <20 Kg", value:"29-Parcel <20 Kg"},
    {label:"30-Container", value:"30-Container"},
    {label:"31-Italy Mixed province", value:"31-Italy Mixed province"},
    {label:"32-40’ Container", value:"32-40’ Container"},
    {label:"33-20’ Container", value:"33-20’ Container"},
    {label:"34-20’ Hand stacked", value:"34-20’ Hand stacked"},
    {label:"35-LCL", value:"35-LCL"},
    {label:"36-ISO Tank", value:"36-ISO Tank"},
    {label:"37-Scheduled pickup", value:"37-Scheduled pickup"},
    {label:"41-PICKUP FTL Road", value:"41-PICKUP FTL Road"},
    {label:"42-PICKUP 40’ Container", value:"42-PICKUP 40’ Container"},
    {label:"43-PICKUP 20’ Container", value:"43-PICKUP 20’ Container"},
    {label:"44-PICKUP 20’ Handstack", value:"44-PICKUP 20’ Handstack"},
    {label:"45-PICKUP LCL", value:"45-PICKUP LCL"},
    {label:"46-PICKUP ISO Tank", value:"46-PICKUP ISO Tank"}
]

export const opt_Incoterm=[
    {label:"CFR - Costs and freight", value:"CFR - Costs and freight"},
    {label:"CIF - Costs, insurance & freight", value:"CIF - Costs, insurance & freight"},
    {label:"CIP - Carriage and insurance paid to", value:"CIP - Carriage and insurance paid to"},
    {label:"CPT - Carriage paid to", value:"CPT - Carriage paid to"},
    {label:"DAF - No longer used", value:"DAF - No longer used"},
    {label:"DAP - Delivered At Place-", value:"DAP - Delivered At Place-"},
    {label:"DAT - DeliveredAtTerminl-", value:"DAT - DeliveredAtTerminl-"},
    {label:"DDP - Delivered Duty Paid", value:"DDP - Delivered Duty Paid"},
    {label:"EXW - Ex Works", value:"EXW - Ex Works"},
    {label:"FAS - Free Alongside Ship", value:"FAS - Free Alongside Ship"},
    {label:"FCA - Free Carrier", value:"FCA - Free Carrier"},
    {label:"FOB - Free on board", value:"FOB - Free on board"}
]

export const opt_Typeofrequest=[
    {label:"New Sold-to setup", value:"New Sold-to setup"},
    {label:"Modify Sold-to setup", value:"Modify Sold-to setup"},
    {label:"New Ship-to setup", value:"New Ship-to setup"},
    {label:"Modify Ship-to setup", value:"Modify Ship-to setup"},
    {label:"New Bill-to setup", value:"New Bill-to setup"},
    {label:"Modify Bill-to setup", value:"Modify Bill-to setup"}
]

export const opt_Salesoffice=[
    {label:"GB04 - UK Cas-Off (Offshore)", value:"GB04 - UK Cas-Off (Offshore)"},
    {label:"GB05 UK Cas-Power (PowerGen)", value:"GB05 UK Cas-Power (PowerGen)"},
    {label:"NO05 - NO Offshore Castrol", value:"NO05 - NO Offshore Castrol"},
    {label:"DK05 - DK Offshore Castrol", value:"DK05 - DK Offshore Castrol"},
    {label:"TR01 - BP Petrolleri A.Ş.", value:"TR01 - BP Petrolleri A.Ş."}
]

export const opt_setuptype=[
    {label:"Vessel Setup", value:"Vessel_Setup"},
    {label:"Vessel Setup with billing address", value:"Vessel Setup with billing address"},
    {label:"Vessel specific billing address", value:"Vessel specific billing address"},
    {label:"Vessel Deletion / close vessel record", value:"Vessel Deletion / close vessel record"},
    {label:"Billing address Setup", value:"Billing address Setup-to_Setup"},
    // {label:"Billing address (Invoice point or Bill-to) Setup", value:"Billing address (Invoice point or Bill-to) Setup-to_Setup"},
    // {label:"Price increase / new discount-matrix and new pricelist", value:"Price increase / new discount-matrix and new pricelist"},
    // {label:"Price increase / new pricelist", value:"Price increase / new pricelist"},
    // {label:"Update Pricelist under Customer", value:"Update Pricelist under Customer"},
    // {label:"Change Discounts", value:"Change Discounts"},
    {label:"New Customer setup", value:"New_Customer_setup"},
    {label:"Amend Customer Setup", value:"Amend Customer Setup"},
    // {label:"Investment setup and/or Rebate Setup", value:"Investment setup and/or Rebate Setup"},
]

export const opt_Currency=[
    {label:"TRY", value:"TRY"},
    {label:"USD", value:"USD"},
    {label:"GBP", value:"GBP"},
    {label:"EUR", value:"EUR"},
    {label:"JPY", value:"JPY"},
    {label:"NOK", value:"NOK"},
    {label:"DKK", value:"DKK"},
    {label:"SEK", value:"SEK"}
]
export const opt_uoa_Currency=[
    {label:"TRY", value:"TRY"},
    {label:"USD", value:"USD"},
    {label:"GBP", value:"GBP"},
    {label:"EUR", value:"EUR"},
    {label:"JPY", value:"JPY"},
    {label:"NOK", value:"NOK"},
    {label:"DKK", value:"DKK"},
    {label:"SEK", value:"SEK"}
]


export const opt_pl=[
    {label:"C+", value:"C+"},
    {label:"YD", value:"YD"},
    {label:"XA", value:"XA"},
    {label:"YC", value:"YC"},
    {label:"XC", value:"XC"},
    {label:"XI", value:"XI"}
]

export const opt_Delivery=[
    {label:"01 - Top", value:"01 - Top"},
    {label:"02  - High", value:"02  - High"},
    {label:"03 - Medium", value:"03 - Medium"},
    {label:"04 - Low", value:"04 - Low"}
]

export const opt_Shippingconditions=[
    {label:"01 Full Truckload", value:"01 Full Truckload"},
    {label:"02 Part Truckload", value:"02 Part Truckload"},
    {label:"03 Pickup", value:"03 Pickup"}
]

export const opt_Delivering_plant=[
    {label:"3000 - ES DISTRW Marina TC Las Palmas", value:"3000 - ES DISTRW Marina TC Las Palmas"},
    {label:"3003 - ES DISTRW Marina Tarragona", value:"3003 - ES DISTRW Marina Tarragona"},
    {label:"3005 - ES DISTRW Camarma", value:"3005 - ES DISTRW Camarma"},
    {label:"3006 - ES DISTRW Marina Algeciras", value:"3006 - ES DISTRW Marina Algeciras"},
    {label:"3009 - ES DISTRW Marina Santander", value:"3009 - ES DISTRW Marina Santander"},
    {label:"3011 - ES DISTRW Marina Tenerife", value:"3011 - ES DISTRW Marina Tenerife"},
    {label:"3012 - PT DISTRW Azambuja", value:"3012 - PT DISTRW Azambuja"},
    {label:"3014 - ES DISTRW DANGEROUS GOODS", value:"3014 - ES DISTRW DANGEROUS GOODS"},
    {label:"3015 - E.DIAZ", value:"3015 - E.DIAZ"},
    {label:"3016 - QUIMIDROGA, SA", value:"3016 - QUIMIDROGA, SA"},
    {label:"3017 - SAPEC QUIMICA, SA", value:"3017 - SAPEC QUIMICA, SA"},
    {label:"3018 - GI Gibraltar warehouse", value:"3018 - GI Gibraltar warehouse"},
    {label:"3019 - GI Gibraltar Barges", value:"3019 - GI Gibraltar Barges"},
    {label:"3020 - GI Gibraltar Marine", value:"3020 - GI Gibraltar Marine"},
    {label:"3025 - BE De Rijke, Gent", value:"3025 - BE De Rijke, Gent"},
    {label:"3026 - BE Van Den Anker", value:"3026 - BE Van Den Anker"},
    {label:"3030 - NL De Rijke, Sluiskil", value:"3030 - NL De Rijke, Sluiskil"},
    {label:"3031 - NL Staalduinen, Maasdijk", value:"3031 - NL Staalduinen, Maasdijk"},
    {label:"3037 - AMI CHIMIE", value:"3037 - AMI CHIMIE"},
    {label:"3050 - DE Luebker Spedition GmbH&CoKG", value:"3050 - DE Luebker Spedition GmbH&CoKG"},
    {label:"3054 - DE Suederelbe Logistik GmbH", value:"3054 - DE Suederelbe Logistik GmbH"},
    {label:"3056 - DE Raben Trans European GmbH", value:"3056 - DE Raben Trans European GmbH"},
    {label:"3058 - DE Schmalstieg Hamburg Harburg", value:"3058 - DE Schmalstieg Hamburg Harburg"},
    {label:"3059 - DE Shipstore Kiel", value:"3059 - DE Shipstore Kiel"},
    {label:"3063 - NL De Rijke, Sluiskil", value:"3063 - NL De Rijke, Sluiskil"},
    {label:"3075 - GB WILLIAMS- SouthamptonMarine", value:"3075 - GB WILLIAMS- SouthamptonMarine"},
    {label:"3076 - GB SELETAR-Great Yarmouth- Mar", value:"3076 - GB SELETAR-Great Yarmouth- Mar"},
    {label:"3077 - GB Univar Ltd", value:"3077 - GB Univar Ltd"},
    {label:"3078 - GB OBAN- UK", value:"3078 - GB OBAN- UK"},
    {label:"3079 - GB LERWICK", value:"3079 - GB LERWICK"},
    {label:"3080 - GB South East Warehouse", value:"3080 - GB South East Warehouse"},
    {label:"3081 - GB TFS The Fulfilment Store", value:"3081 - GB TFS The Fulfilment Store"},
    {label:"3082 - IT IRS Warehouse", value:"3082 - IT IRS Warehouse"},
    {label:"3083 - NON USARE", value:"3083 - NON USARE"},
    {label:"3084 - italiana petroli S.p.A", value:"3084 - italiana petroli S.p.A"},
    {label:"3085 - IE Tanker Plant", value:"3085 - IE Tanker Plant"},
    {label:"3086 - DHL Supply Chain", value:"3086 - DHL Supply Chain"},
    {label:"3087 - GB Ellesmere Port Warehouse", value:"3087 - GB Ellesmere Port Warehouse"},
    {label:"3088 - GB ASCO- Marine- Peterhead", value:"3088 - GB ASCO- Marine- Peterhead"},
    {label:"3089 - GB STREAMLINE- Aberdeen Marine", value:"3089 - GB STREAMLINE- Aberdeen Marine"},
    {label:"3090 - IT Societa Lubrificanti Intern", value:"3090 - IT Societa Lubrificanti Intern"},
    {label:"3092 - BE VLS, Gent", value:"3092 - BE VLS, Gent"},
    {label:"3093 - BE Distrilog, Gent", value:"3093 - BE Distrilog, Gent"},
    {label:"3094 - ES TW CABANILLAS", value:"3094 - ES TW CABANILLAS"},
    {label:"3095 - PT TW BENAVENTE", value:"3095 - PT TW BENAVENTE"},
    {label:"3096 - DE Noerpel GmbH", value:"3096 - DE Noerpel GmbH"},
    {label:"3097 - NEXCEL Reading", value:"3097 - NEXCEL Reading"},
    {label:"3098 - IT Arcese Warehouse", value:"3098 - IT Arcese Warehouse"},
    {label:"3099 - DE Rowe Mineraloelwerk GmbH", value:"3099 - DE Rowe Mineraloelwerk GmbH"},
    {label:"3401 - DK Marine Depot Esbjerg", value:"3401 - DK Marine Depot Esbjerg"},
    {label:"3403 - DK 3rd party Brenntag", value:"3403 - DK 3rd party Brenntag"},
    {label:"3404 - FI Marine Depot Finland", value:"3404 - FI Marine Depot Finland"},
    {label:"3405 - NO Marine Depot Kristansund", value:"3405 - NO Marine Depot Kristansund"},
    {label:"3406 - NO Marine Depot Bergen", value:"3406 - NO Marine Depot Bergen"},
    {label:"3407 - NO Marine Depot Tananger", value:"3407 - NO Marine Depot Tananger"},
    {label:"3408 - NO Marine Depot Tromsø", value:"3408 - NO Marine Depot Tromsø"},
    {label:"3409 - SE Marine Depot Gothenburg", value:"3409 - SE Marine Depot Gothenburg"},
    {label:"3410 - SE 3rd party Torslanda", value:"3410 - SE 3rd party Torslanda"},
    {label:"3411 - SE 3rd party Haanpaa", value:"3411 - SE 3rd party Haanpaa"},
    {label:"3504 - DE Vopak Dupeg Terminal", value:"3504 - DE Vopak Dupeg Terminal"},
    {label:"3505 - DE Gaetckes TREFFPACK", value:"3505 - DE Gaetckes TREFFPACK"},
    {label:"3507 - DE Siebert GmbH", value:"3507 - DE Siebert GmbH"},
    {label:"3508 - DE BCD Chemie GmbH", value:"3508 - DE BCD Chemie GmbH"},
    {label:"3509 - DE Castrol Industrie&Services", value:"3509 - DE Castrol Industrie&Services"},
    {label:"3510 - DE Aerochemica Dr. Deppe GmbH", value:"3510 - DE Aerochemica Dr. Deppe GmbH"},
    {label:"3511 - DE Schaaff & Meurer GmbH", value:"3511 - DE Schaaff & Meurer GmbH"},
    {label:"3512 - DE Loop GmbH", value:"3512 - DE Loop GmbH"},
    {label:"3513 - DE Rettner GmbH", value:"3513 - DE Rettner GmbH"},
    {label:"3514 - DE DECO-PACK GmbH", value:"3514 - DE DECO-PACK GmbH"},
    {label:"3516 - DE ALS Schmiertechnik", value:"3516 - DE ALS Schmiertechnik"},
    {label:"3517 - DE Lohnpack GmbH", value:"3517 - DE Lohnpack GmbH"},
    {label:"3518 - DE (CH) Simatec ag", value:"3518 - DE (CH) Simatec ag"},
    {label:"3519 - DE (FR) Setral S.à.r.l.", value:"3519 - DE (FR) Setral S.à.r.l."},
    {label:"3520 - DE Schmalstieg Hamburg Neuhof", value:"3520 - DE Schmalstieg Hamburg Neuhof"},
    {label:"3521 - DE Atlantic MineraloelwerkGmbH", value:"3521 - DE Atlantic MineraloelwerkGmbH"},
    {label:"3522 - DE Carl Bechem GmbH", value:"3522 - DE Carl Bechem GmbH"},
    {label:"3523 - DE BLOCK Schmierstoff GmbH", value:"3523 - DE BLOCK Schmierstoff GmbH"},
    {label:"3525 - DE ML Lubrication GmbH", value:"3525 - DE ML Lubrication GmbH"},
    {label:"3526 - DE WIGO Chemie GmbH", value:"3526 - DE WIGO Chemie GmbH"},
    {label:"3527 - DE Schlenk Metallic Pigments", value:"3527 - DE Schlenk Metallic Pigments"},
    {label:"3528 - DE ECKART GmbH", value:"3528 - DE ECKART GmbH"},
    {label:"3601 - US DISTRW XPO LOGISTICS", value:"3601 - US DISTRW XPO LOGISTICS"},
    {label:"3602 - DISTRW Safety Kleen - St Rose", value:"3602 - DISTRW Safety Kleen - St Rose"},
    {label:"3603 - US DISTRW - Jacobson Levittown", value:"3603 - US DISTRW - Jacobson Levittown"},
    {label:"3604 - US DISTRW BARRETT DIST-MEMPHIS", value:"3604 - US DISTRW BARRETT DIST-MEMPHIS"},
    {label:"3605 - Newport, Chicago", value:"3605 - Newport, Chicago"},
    {label:"3606 - Newport, Channelview", value:"3606 - Newport, Channelview"},
    {label:"3607 - Newport, Detroit", value:"3607 - Newport, Detroit"},
    {label:"3608 - US DISTRW CALUMET WAREHOUSE", value:"3608 - US DISTRW CALUMET WAREHOUSE"},
    {label:"3609 - CA DISTRW MTE Logistix-Calgary", value:"3609 - CA DISTRW MTE Logistix-Calgary"},
    {label:"3612 - US DISTRW - Panalpina", value:"3612 - US DISTRW - Panalpina"},
    {label:"3614 - CA DISTRW - Wakefield Edmonton", value:"3614 - CA DISTRW - Wakefield Edmonton"},
    {label:"3615 - US DISTRW Western Logistics", value:"3615 - US DISTRW Western Logistics"},
    {label:"3617 - US DISTRW CATCH UP LOGISTICS", value:"3617 - US DISTRW CATCH UP LOGISTICS"},
    {label:"3618 - US DISTRW Clean Harbor", value:"3618 - US DISTRW Clean Harbor"},
    {label:"3619 - US DSITRW REO Proc LA", value:"3619 - US DSITRW REO Proc LA"},
    {label:"3620 - DISTRW EXPEDITORS -NEW ORLEANS", value:"3620 - DISTRW EXPEDITORS -NEW ORLEANS"},
    {label:"3621 - DISTRW EXPEDITORS - Port Allen", value:"3621 - DISTRW EXPEDITORS - Port Allen"},
    {label:"3623 - US DISTRW Gehring Montgomery", value:"3623 - US DISTRW Gehring Montgomery"},
    {label:"3625 - Newport, Linden", value:"3625 - Newport, Linden"},
    {label:"3626 - US DISTRW MARTIN MID-GALVESTON", value:"3626 - US DISTRW MARTIN MID-GALVESTON"},
    {label:"3627 - DISTRW MAXUM PETROLEUM-SEATTLE", value:"3627 - DISTRW MAXUM PETROLEUM-SEATTLE"},
    {label:"3629 - US DISTRW PINNACLE OIL Allison", value:"3629 - US DISTRW PINNACLE OIL Allison"},
    {label:"3630 - US DISTRW PPC (WARMINSTER)", value:"3630 - US DISTRW PPC (WARMINSTER)"},
    {label:"3631 - SONOCO CORRFLEX WINSTON SALEM", value:"3631 - SONOCO CORRFLEX WINSTON SALEM"},
    {label:"3632 - DISTRW TT&H/ Expeditors - BTR", value:"3632 - DISTRW TT&H/ Expeditors - BTR"},
    {label:"3633 - 3PLM AMERICAN REFINING GRP ARG", value:"3633 - 3PLM AMERICAN REFINING GRP ARG"},
    {label:"3634 - US 3PLM CALUMET PACKAGING", value:"3634 - US 3PLM CALUMET PACKAGING"},
    {label:"3639 - US 3PLM CHS - Kenton, OHIO", value:"3639 - US 3PLM CHS - Kenton, OHIO"},
    {label:"3640 - 3PLM COMPLEX CHEMICALS-TALLULA", value:"3640 - 3PLM COMPLEX CHEMICALS-TALLULA"},
    {label:"3641 - US 3PLM Faspak", value:"3641 - US 3PLM Faspak"},
    {label:"3642 - GME 3PLM Gordon Terminal-BAYON", value:"3642 - GME 3PLM Gordon Terminal-BAYON"},
    {label:"3643 - US 3PLM INTERLUBE", value:"3643 - US 3PLM INTERLUBE"},
    {label:"3645 - GME MARTIN MIDSTREAM - HOUSTON", value:"3645 - GME MARTIN MIDSTREAM - HOUSTON"},
    {label:"3646 - 3PLM MAXUM PETROLEUM - COMPTON", value:"3646 - 3PLM MAXUM PETROLEUM - COMPTON"},
    {label:"3648 - US 3PLM ORREX PLASTICS COMPANY", value:"3648 - US 3PLM ORREX PLASTICS COMPANY"},
    {label:"3650 - US 3PLM PINNACLE OIL W 81ST", value:"3650 - US 3PLM PINNACLE OIL W 81ST"},
    {label:"3651 - GME SAS - N. Carolina", value:"3651 - GME SAS - N. Carolina"},
    {label:"3652 - GME SAS - HOUSTON", value:"3652 - GME SAS - HOUSTON"},
    {label:"3653 - 3PLM SHEPHERD CHEMICAL COMPANY", value:"3653 - 3PLM SHEPHERD CHEMICAL COMPANY"},
    {label:"3654 - 3PLM SONOCO CORRFLEX-RURAL HAL", value:"3654 - 3PLM SONOCO CORRFLEX-RURAL HAL"},
    {label:"3655 - Pack Logix LLC", value:"3655 - Pack Logix LLC"},
    {label:"3657 - US 3PLM THIRD COAST TERMINALS", value:"3657 - US 3PLM THIRD COAST TERMINALS"},
    {label:"3658 - US 3PLM PCA - Atlanta  ", value:"3658 - US 3PLM PCA - Atlanta  "},
    {label:"3659 - US 3PLM PCA - Hanover  ", value:"3659 - US 3PLM PCA - Hanover  "},
    {label:"3660 - US 3PLM PCA - Santa Fe Springs", value:"3660 - US 3PLM PCA - Santa Fe Springs"},
    {label:"3661 - US 3PLM ZXP Technologies LTD", value:"3661 - US 3PLM ZXP Technologies LTD"},
    {label:"3662 - GME BELLE CHASSE - HARVEY", value:"3662 - GME BELLE CHASSE - HARVEY"},
    {label:"3663 - Marine Colonial Oil- SAVANNAH", value:"3663 - Marine Colonial Oil- SAVANNAH"},
    {label:"3665 - GME MARINE OIL SERVICE -BOSTON", value:"3665 - GME MARINE OIL SERVICE -BOSTON"},
    {label:"3666 - GME MARINE OIL SERVICE-BALTIMO", value:"3666 - GME MARINE OIL SERVICE-BALTIMO"},
    {label:"3667 - GME Marine Oil Service -LINDEN", value:"3667 - GME Marine Oil Service -LINDEN"},
    {label:"3668 - GME Marine Oil Service-Norfolk", value:"3668 - GME Marine Oil Service-Norfolk"},
    {label:"3669 - MARINE OIL SERVICE -WILMINGTON", value:"3669 - MARINE OIL SERVICE -WILMINGTON"},
    {label:"3670 - GME MARTIN MIDSTREAM -THEODORE", value:"3670 - GME MARTIN MIDSTREAM -THEODORE"},
    {label:"3671 - Martin Energy Services", value:"3671 - Martin Energy Services"},
    {label:"3672 - US DSV Old World Industries", value:"3672 - US DSV Old World Industries"},
    {label:"3673 - GME SSI PETROLEUM -BELLE GLADE", value:"3673 - GME SSI PETROLEUM -BELLE GLADE"},
    {label:"3674 - SSI PETROLEUM - JACKSONVILLE", value:"3674 - SSI PETROLEUM - JACKSONVILLE"},
    {label:"3675 - GME SSI PETROLEUM-WINTER HAVEN", value:"3675 - GME SSI PETROLEUM-WINTER HAVEN"},
    {label:"3676 - 3PLM Axel Americas-Mississippi", value:"3676 - 3PLM Axel Americas-Mississippi"},
    {label:"3697 - 3PLM Safety Kleen - Metairie", value:"3697 - 3PLM Safety Kleen - Metairie"},
    {label:"3698 - CA 3PLM Wakefield Canada Inc.", value:"3698 - CA 3PLM Wakefield Canada Inc."},
    {label:"3699 - WARREN DISTRIBUTION - GLENDALE", value:"3699 - WARREN DISTRIBUTION - GLENDALE"},
    {label:"3703 - DISTRW BUSLER WAREHOUSE", value:"3703 - DISTRW BUSLER WAREHOUSE"},
    {label:"3704 - US DISTRW XPO LOGISTICS - LA", value:"3704 - US DISTRW XPO LOGISTICS - LA"},
    {label:"3705 - US DISTRW REO Proc TX", value:"3705 - US DISTRW REO Proc TX"},
    {label:"3706 - US DISTRW XPO LOGISTICS - PA", value:"3706 - US DISTRW XPO LOGISTICS - PA"},
    {label:"3707 - US CATCHUP LOGISTICS", value:"3707 - US CATCHUP LOGISTICS"},
    {label:"3708 - US DISTRW EXPEDITORS–Jourdan", value:"3708 - US DISTRW EXPEDITORS–Jourdan"},
    {label:"3709 - US MARINE OIL SERVS-ELIZABETH", value:"3709 - US MARINE OIL SERVS-ELIZABETH"},
    {label:"3710 - US DISTRW EXPEDITORS-Nike Buld", value:"3710 - US DISTRW EXPEDITORS-Nike Buld"},
    {label:"3711 - US DISTRW EXPEDITORS - Old Gen", value:"3711 - US DISTRW EXPEDITORS - Old Gen"},
    {label:"3712 - US DISTRW Expeditors - FL Ave", value:"3712 - US DISTRW Expeditors - FL Ave"},
    {label:"3713 - US ZXP - BAYTOWN", value:"3713 - US ZXP - BAYTOWN"},
    {label:"3715 - GME SAS - HOUSTON", value:"3715 - GME SAS - HOUSTON"},
    {label:"4000 - ES LOBP Lubrisur", value:"4000 - ES LOBP Lubrisur"},
    {label:"4020 - BE Gent Lubes Plant", value:"4020 - BE Gent Lubes Plant"},
    {label:"4021 - BE Antwerp Lubes Plant", value:"4021 - BE Antwerp Lubes Plant"},
    {label:"4022 - TR GEMLlK", value:"4022 - TR GEMLlK"},
    {label:"4041 - DE BP Europa SE HH Neuhof", value:"4041 - DE BP Europa SE HH Neuhof"},
    {label:"4042 - DE H&R Salzbergen", value:"4042 - DE H&R Salzbergen"},
    {label:"4043 - DE BP Europa SE MGB", value:"4043 - DE BP Europa SE MGB"},
    {label:"4044 - DE BP Europa SE Landau", value:"4044 - DE BP Europa SE Landau"},
    {label:"4045 - DE H&R Hamburg Neuhof", value:"4045 - DE H&R Hamburg Neuhof"},
    {label:"4060 - FR Peronne Lubes Plant", value:"4060 - FR Peronne Lubes Plant"},
    {label:"4071 - IT BP Italia Plant", value:"4071 - IT BP Italia Plant"},
    {label:"4101 - BP LUBRICANTS USA BATON ROUGE", value:"4101 - BP LUBRICANTS USA BATON ROUGE"},
    {label:"4102 - BP Lubricants USA WARMINSTER", value:"4102 - BP Lubricants USA WARMINSTER"},
    {label:"4103 - BP LUBRICANTS USA - BALTIMORE", value:"4103 - BP LUBRICANTS USA - BALTIMORE"},
    {label:"4104 - BP Lubricants USA LUBECON", value:"4104 - BP Lubricants USA LUBECON"},
    {label:"7501 - DFF APACHE OIL COMPAN-PASADENA", value:"7501 - DFF APACHE OIL COMPAN-PASADENA"},
    {label:"7502 - DFF APOLLO OIL LLC-LOUISVILLE", value:"7502 - DFF APOLLO OIL LLC-LOUISVILLE"},
    {label:"7503 - DFF Pugh Lubricants", value:"7503 - DFF Pugh Lubricants"},
    {label:"7505 - US DFF APOLLO OIL LLC NITRO", value:"7505 - US DFF APOLLO OIL LLC NITRO"},
    {label:"7506 - DFF APOLLO OIL LLC-WINCHESTER", value:"7506 - DFF APOLLO OIL LLC-WINCHESTER"},
    {label:"7507 - DFF ARNOLD OIL- CORPUS CHRISTI", value:"7507 - DFF ARNOLD OIL- CORPUS CHRISTI"},
    {label:"7508 - US DFF ARNOLD OIL CO MERCEDES", value:"7508 - US DFF ARNOLD OIL CO MERCEDES"},
    {label:"7510 - DFF ARNOLD OIL COMPANY- AUSTIN", value:"7510 - DFF ARNOLD OIL COMPANY- AUSTIN"},
    {label:"7511 - DFF ARNOLD OIL - SAN ANTONIO", value:"7511 - DFF ARNOLD OIL - SAN ANTONIO"},
    {label:"7512 - US DFF ARNOLD OIL COMPANY-WACO", value:"7512 - US DFF ARNOLD OIL COMPANY-WACO"},
    {label:"7513 - US DFF ARNOLD OIL - HOUSTON", value:"7513 - US DFF ARNOLD OIL - HOUSTON"},
    {label:"7514 - DFF AUTO AND IND BILLIN-YSTONE", value:"7514 - DFF AUTO AND IND BILLIN-YSTONE"},
    {label:"7515 - DFF AUTOMOTIVE AND INDUS-BOISE", value:"7515 - DFF AUTOMOTIVE AND INDUS-BOISE"},
    {label:"7516 - US DFF AUTO AND INDUST SPOKANE", value:"7516 - US DFF AUTO AND INDUST SPOKANE"},
    {label:"7517 - DFF AUTO AND IND - CHUBBUCK", value:"7517 - DFF AUTO AND IND - CHUBBUCK"},
    {label:"7518 - DFF AUTO IND TIGARD & PORTLAND", value:"7518 - DFF AUTO IND TIGARD & PORTLAND"},
    {label:"7520 - DFF B AND M OIL CO -FORT SMITH", value:"7520 - DFF B AND M OIL CO -FORT SMITH"},
    {label:"7521 - DFF B AND M OIL COMPANY-CONWAY", value:"7521 - DFF B AND M OIL COMPANY-CONWAY"},
    {label:"7522 - DFF B AND M OIL-OKLAHOMA CITY", value:"7522 - DFF B AND M OIL-OKLAHOMA CITY"},
    {label:"7523 - DFF BILLS BATTERY - CINCINNATI", value:"7523 - DFF BILLS BATTERY - CINCINNATI"},
    {label:"7525 - DFF CENTRAL OIL & SUPPLY- BTR", value:"7525 - DFF CENTRAL OIL & SUPPLY- BTR"},
    {label:"7526 - DFF CENTRAL OIL SUPPLY -MONROE", value:"7526 - DFF CENTRAL OIL SUPPLY -MONROE"},
    {label:"7527 - DFF CENTRAL OIL&SUP-SHREVEPORT", value:"7527 - DFF CENTRAL OIL&SUP-SHREVEPORT"},
    {label:"7530 - DFF COLORADO COUNTY OIL-COLUMB", value:"7530 - DFF COLORADO COUNTY OIL-COLUMB"},
    {label:"7531 - DFF COLORADO PETROLEUM- DENVER", value:"7531 - DFF COLORADO PETROLEUM- DENVER"},
    {label:"7532 - DFF COLUMBUS OIL CO - COLUMBUS", value:"7532 - DFF COLUMBUS OIL CO - COLUMBUS"},
    {label:"7533 - DFF CONSERVANCY OIL-ALBUQUERQU", value:"7533 - DFF CONSERVANCY OIL-ALBUQUERQU"},
    {label:"7534 - DFF CONSERVANCY OIL - DURANGO", value:"7534 - DFF CONSERVANCY OIL - DURANGO"},
    {label:"7535 - DFF CONSERVANCY-GRAND JUNCTION", value:"7535 - DFF CONSERVANCY-GRAND JUNCTION"},
    {label:"7536 - DFF CORRIGAN OIL-WHITMORE LAKE", value:"7536 - DFF CORRIGAN OIL-WHITMORE LAKE"},
    {label:"7537 - US DFF CREST DISTRIB PROVO", value:"7537 - US DFF CREST DISTRIB PROVO"},
    {label:"7539 - US DFF DIAMOND OIL-DES MOINES", value:"7539 - US DFF DIAMOND OIL-DES MOINES"},
    {label:"7540 - DFF DIAMOND OIL CO - LINCOLN", value:"7540 - DFF DIAMOND OIL CO - LINCOLN"},
    {label:"7541 - DFF DYSARTS SERVICE INC-HERMON", value:"7541 - DFF DYSARTS SERVICE INC-HERMON"},
    {label:"7542 - DFF EMERSON OIL CO - ROCHESTER", value:"7542 - DFF EMERSON OIL CO - ROCHESTER"},
    {label:"7543 - DFF ENTERPRISE OIL CO -CHICAGO", value:"7543 - DFF ENTERPRISE OIL CO -CHICAGO"},
    {label:"7544 - DFF FAUSER OIL COMPANY-VINTON", value:"7544 - DFF FAUSER OIL COMPANY-VINTON"},
    {label:"7545 - DFF FLAMINGO OIL CORP- MIAMI", value:"7545 - DFF FLAMINGO OIL CORP- MIAMI"},
    {label:"7547 - DFF GAUBERT OIL CO - THIBODAUX", value:"7547 - DFF GAUBERT OIL CO - THIBODAUX"},
    {label:"7550 - DFF HALCO INDUSTRIES-NORCROSS", value:"7550 - DFF HALCO INDUSTRIES-NORCROSS"},
    {label:"7551 - DFF HARTOG OIL CO- SAINT LOUIS", value:"7551 - DFF HARTOG OIL CO- SAINT LOUIS"},
    {label:"7552 - US DFF HASCO OIL DENVER", value:"7552 - US DFF HASCO OIL DENVER"},
    {label:"7554 - DFF H B WAREHOUSE INC-BEDFORD", value:"7554 - DFF H B WAREHOUSE INC-BEDFORD"},
    {label:"7555 - DFF HEATHWOOD OIL- KANSAS CITY", value:"7555 - DFF HEATHWOOD OIL- KANSAS CITY"},
    {label:"7556 - DFF HUNTER OIL - CHATTANOOGA", value:"7556 - DFF HUNTER OIL - CHATTANOOGA"},
    {label:"7557 - DFF HUNTER OIL CO-EVERGREEN", value:"7557 - DFF HUNTER OIL CO-EVERGREEN"},
    {label:"7558 - DFF HUNTER OIL COMPANY-IRONDAL", value:"7558 - DFF HUNTER OIL COMPANY-IRONDAL"},
    {label:"7559 - DFF DELTA WESTERN-ANCHORAGE", value:"7559 - DFF DELTA WESTERN-ANCHORAGE"},
    {label:"7560 - DFF INTERSTATE OIL COMPAN-ELKO", value:"7560 - DFF INTERSTATE OIL COMPAN-ELKO"},
    {label:"7561 - DFF INTERSTATE OIL CO - FRESNO", value:"7561 - DFF INTERSTATE OIL CO - FRESNO"},
    {label:"7562 - DFF INTERSTATE OIL CO -REDDING", value:"7562 - DFF INTERSTATE OIL CO -REDDING"},
    {label:"7563 - US DFF INTERSTATE OIL-ELK GROV", value:"7563 - US DFF INTERSTATE OIL-ELK GROV"},
    {label:"7564 - DFF INTERSTATE OIL CO - SPARKS", value:"7564 - DFF INTERSTATE OIL CO - SPARKS"},
    {label:"7565 - US DFF ISGETT DIST ASHEVILLE", value:"7565 - US DFF ISGETT DIST ASHEVILLE"},
    {label:"7566 - DFF ISLAND OIL & SUPP-HONOLULU", value:"7566 - DFF ISLAND OIL & SUPP-HONOLULU"},
    {label:"7567 - DFF JACK BECKER - JACKSONVILLE", value:"7567 - DFF JACK BECKER - JACKSONVILLE"},
    {label:"7568 - DFF JB DEWAR - SAN LUIS OBISPO", value:"7568 - DFF JB DEWAR - SAN LUIS OBISPO"},
    {label:"7571 - DFF JONES OIL COMPANY-RICHMOND", value:"7571 - DFF JONES OIL COMPANY-RICHMOND"},
    {label:"7573 - DFF LARD OIL CO-DENHAM SPRINGS", value:"7573 - DFF LARD OIL CO-DENHAM SPRINGS"},
    {label:"7574 - DFF RAINIER PETROLEUM-SEATTLE", value:"7574 - DFF RAINIER PETROLEUM-SEATTLE"},
    {label:"7584 - DFF MIELKE OIL CO-LITTLE FALLS", value:"7584 - DFF MIELKE OIL CO-LITTLE FALLS"},
    {label:"7585 - US DFF MOTOR OIL SUPPLY KENT", value:"7585 - US DFF MOTOR OIL SUPPLY KENT"},
    {label:"7586 - DFF M S C DISTRIBUTING-PHOENIX", value:"7586 - DFF M S C DISTRIBUTING-PHOENIX"},
    {label:"7587 - US DFF NEWTON OIL CO LAFAYETTE", value:"7587 - US DFF NEWTON OIL CO LAFAYETTE"},
    {label:"7588 - US DFF NE LUBRICANTS CHARLOTTE", value:"7588 - US DFF NE LUBRICANTS CHARLOTTE"},
    {label:"7589 - US DFF NE LUBRICANTS RICHMOND", value:"7589 - US DFF NE LUBRICANTS RICHMOND"},
    {label:"7590 - DFF NORTHEAST LUB-CLEVELAND", value:"7590 - DFF NORTHEAST LUB-CLEVELAND"},
    {label:"7591 - US DFF NE LUBRICANTS DORAVILLE", value:"7591 - US DFF NE LUBRICANTS DORAVILLE"},
    {label:"7592 - DFF OAKLAND LUBRICATION", value:"7592 - DFF OAKLAND LUBRICATION"},
    {label:"7593 - DFF TOTAL ENERGY-N KINGSTOWN", value:"7593 - DFF TOTAL ENERGY-N KINGSTOWN"},
    {label:"7594 - DFF ORANGE LINE OIL CO -POMONA", value:"7594 - DFF ORANGE LINE OIL CO -POMONA"},
    {label:"7595 - DFF ORANGE LINE OIL CO-GLENDAL", value:"7595 - DFF ORANGE LINE OIL CO-GLENDAL"},
    {label:"7596 - DFF ORANGE LINE OIL-HENDERSON", value:"7596 - DFF ORANGE LINE OIL-HENDERSON"},
    {label:"7597 - DFF PARENT PETROLEUM-ST CHARLE", value:"7597 - DFF PARENT PETROLEUM-ST CHARLE"},
    {label:"7598 - DFF PARKER OIL COMPANY-WICHITA", value:"7598 - DFF PARKER OIL COMPANY-WICHITA"},
    {label:"7599 - DFF PARKER OIL - KANSAS CITY", value:"7599 - DFF PARKER OIL - KANSAS CITY"},
    {label:"7600 - DFF PARMAN ENERGY CO-NASHVILLE", value:"7600 - DFF PARMAN ENERGY CO-NASHVILLE"},
    {label:"7601 - DFF PARMAN ENERGY-OLIVE BRANCH", value:"7601 - DFF PARMAN ENERGY-OLIVE BRANCH"},
    {label:"7602 - US DFF PETROCHOICE CHISHOLM", value:"7602 - US DFF PETROCHOICE CHISHOLM"},
    {label:"7603 - US DFF PETROCHOICE-GRAND FORKS", value:"7603 - US DFF PETROCHOICE-GRAND FORKS"},
    {label:"7604 - US DFF PETROCHOICE NEGAUNEE", value:"7604 - US DFF PETROCHOICE NEGAUNEE"},
    {label:"7605 - DFF PETROCHOICE-NORTHFIELD", value:"7605 - DFF PETROCHOICE-NORTHFIELD"},
    {label:"7606 - US DFF PETROCHOICE SUPERIOR", value:"7606 - US DFF PETROCHOICE SUPERIOR"},
    {label:"7607 - DFF PETROCHOICE - BLOUNTVILLE", value:"7607 - DFF PETROCHOICE - BLOUNTVILLE"},
    {label:"7608 - DFF PETROCHOICE - KNOXVILLE", value:"7608 - DFF PETROCHOICE - KNOXVILLE"},
    {label:"7609 - DFF PETRO LOCK INC-BAKERSFIELD", value:"7609 - DFF PETRO LOCK INC-BAKERSFIELD"},
    {label:"7610 - DFF PETRO LOCK INC LANCASTER", value:"7610 - DFF PETRO LOCK INC LANCASTER"},
    {label:"7611 - DFF PIONEER DISTRIB - PHOENIX", value:"7611 - DFF PIONEER DISTRIB - PHOENIX"},
    {label:"7612 - DFF PORT CONSOLIDATED-FT MYERS", value:"7612 - DFF PORT CONSOLIDATED-FT MYERS"},
    {label:"7613 - DFF PORT CONSOLIDATED -GRVLAND", value:"7613 - DFF PORT CONSOLIDATED -GRVLAND"},
    {label:"7614 - DFF PORT CONSOLIDATED- JACKSON", value:"7614 - DFF PORT CONSOLIDATED- JACKSON"},
    {label:"7616 - DFF PORT CONSOLIDATED-ORLANDO", value:"7616 - DFF PORT CONSOLIDATED-ORLANDO"},
    {label:"7617 - DFF PORT CONSOLIDATED-FRT LAUD", value:"7617 - DFF PORT CONSOLIDATED-FRT LAUD"},
    {label:"7618 - DFF PORT CONSOLIDATED - TAMPA1", value:"7618 - DFF PORT CONSOLIDATED - TAMPA1"},
    {label:"7619 - DFF PORT CONSOLIDATED - TAMPA2", value:"7619 - DFF PORT CONSOLIDATED - TAMPA2"},
    {label:"7620 - DFF PPC LUBRICANTS - BALTIMORE", value:"7620 - DFF PPC LUBRICANTS - BALTIMORE"},
    {label:"7621 - DFF PPC LUBRICANTS INC- BUTLER", value:"7621 - DFF PPC LUBRICANTS INC- BUTLER"},
    {label:"7622 - DFF PPC LUBRICANTS - JONESTOWN", value:"7622 - DFF PPC LUBRICANTS - JONESTOWN"},
    {label:"7623 - DFF PPC LUBRICANTS- WARMINSTER", value:"7623 - DFF PPC LUBRICANTS- WARMINSTER"},
    {label:"7624 - US DFF PRIME LUBE INC CARTERET", value:"7624 - US DFF PRIME LUBE INC CARTERET"},
    {label:"7625 - US DFF PRIME LUBE INC AVENEL", value:"7625 - US DFF PRIME LUBE INC AVENEL"},
    {label:"7626 - US DFF PUGH OIL  INC ASHEBORO", value:"7626 - US DFF PUGH OIL  INC ASHEBORO"},
    {label:"7627 - DFF PUGH OIL CO INC-CHARLESTON", value:"7627 - DFF PUGH OIL CO INC-CHARLESTON"},
    {label:"7628 - US DFF PUGH OIL CO INC ASHLAND", value:"7628 - US DFF PUGH OIL CO INC ASHLAND"},
    {label:"7629 - US DFF R D HOLDER SPRINGFIELD", value:"7629 - US DFF R D HOLDER SPRINGFIELD"},
    {label:"7630 - US DFF R D HOLDER NEW CARLISLE", value:"7630 - US DFF R D HOLDER NEW CARLISLE"},
    {label:"7631 - DFF REISNER DISTRIB-BELLINGHAM", value:"7631 - DFF REISNER DISTRIB-BELLINGHAM"},
    {label:"7633 - DFF RIVER CITY PETRO-LAS VEGAS", value:"7633 - DFF RIVER CITY PETRO-LAS VEGAS"},
    {label:"7634 - DFF R V MOORE - NEW LEXINGTON", value:"7634 - DFF R V MOORE - NEW LEXINGTON"},
    {label:"7635 - US DFF SC FUELS EL CAJON", value:"7635 - US DFF SC FUELS EL CAJON"},
    {label:"7636 - US DFF SC FUELS MODESTO", value:"7636 - US DFF SC FUELS MODESTO"},
    {label:"7637 - US DFF SC FUELS OXNARD", value:"7637 - US DFF SC FUELS OXNARD"},
    {label:"7638 - DFF SC FUELS-RANCHO DOMINGUEZ", value:"7638 - DFF SC FUELS-RANCHO DOMINGUEZ"},
    {label:"7639 - US DFF SC FUELS RICHMOND", value:"7639 - US DFF SC FUELS RICHMOND"},
    {label:"7640 - DFF SC FUELS - SAN JOSE", value:"7640 - DFF SC FUELS - SAN JOSE"},
    {label:"7641 - DFF SCHWEBEL PETRO-BAKERSFIELD", value:"7641 - DFF SCHWEBEL PETRO-BAKERSFIELD"},
    {label:"7642 - US DFF SEABOARD DISTRIBUTION", value:"7642 - US DFF SEABOARD DISTRIBUTION"},
    {label:"7643 - DFF SMITTYS SUPPLY- ROSELAND", value:"7643 - DFF SMITTYS SUPPLY- ROSELAND"},
    {label:"7644 - DFF SSI LUBRICANTS-BELLE GLADE", value:"7644 - DFF SSI LUBRICANTS-BELLE GLADE"},
    {label:"7645 - DFF SSI LUBRICANTS-JACKSONVILL", value:"7645 - DFF SSI LUBRICANTS-JACKSONVILL"},
    {label:"7646 - DFF SSI LUBRICANTS-WINTER HAVE", value:"7646 - DFF SSI LUBRICANTS-WINTER HAVE"},
    {label:"7647 - DFF STERLING PETROLEUM-NEW ORL", value:"7647 - DFF STERLING PETROLEUM-NEW ORL"},
    {label:"7648 - DFF SUPERIOR LUBRI - TONAWANDA", value:"7648 - DFF SUPERIOR LUBRI - TONAWANDA"},
    {label:"7649 - US DFF THREE L INC HOUSTON", value:"7649 - US DFF THREE L INC HOUSTON"},
    {label:"7650 - DFF US VENTURE DBA-KIMBERLY", value:"7650 - DFF US VENTURE DBA-KIMBERLY"},
    {label:"7651 - US DFF VENTO DST CORP GUAYNABO", value:"7651 - US DFF VENTO DST CORP GUAYNABO"},
    {label:"7654 - CA DFF WAKEFIELD - EDMONTON", value:"7654 - CA DFF WAKEFIELD - EDMONTON"},
    {label:"7655 - CA DFF WAKEFIELD - VICTORIA", value:"7655 - CA DFF WAKEFIELD - VICTORIA"},
    {label:"7656 - CA DFF WAKEFIELD -  WINNIPEG", value:"7656 - CA DFF WAKEFIELD -  WINNIPEG"},
    {label:"7657 - CA DFF WAKEFIELD -FREDERICTON", value:"7657 - CA DFF WAKEFIELD -FREDERICTON"},
    {label:"7660 - CA DFF WAKEFIELD - TORONTO", value:"7660 - CA DFF WAKEFIELD - TORONTO"},
    {label:"7662 - CA DFF WAKEFIELD CANADA -LAVAL", value:"7662 - CA DFF WAKEFIELD CANADA -LAVAL"},
    {label:"7664 - DFF WARING OIL COMPANY-BILOXI", value:"7664 - DFF WARING OIL COMPANY-BILOXI"},
    {label:"7665 - DFF WARING OIL COMPANY-FLOWOOD", value:"7665 - DFF WARING OIL COMPANY-FLOWOOD"},
    {label:"7666 - DFF WARING OIL CO -LOUISVILLE", value:"7666 - DFF WARING OIL CO -LOUISVILLE"},
    {label:"7667 - DFF WARING OIL COMPANY-TUPELO", value:"7667 - DFF WARING OIL COMPANY-TUPELO"},
    {label:"7669 - US DFF WESTERN MARKETING", value:"7669 - US DFF WESTERN MARKETING"},
    {label:"7670 - DFF WESTERN MARKETING-LONGVIEW", value:"7670 - DFF WESTERN MARKETING-LONGVIEW"},
    {label:"7672 - DFF WESTERN MARKETING-MONAHANS", value:"7672 - DFF WESTERN MARKETING-MONAHANS"},
    {label:"7674 - DFF WESTERN MARKETING - STROUD", value:"7674 - DFF WESTERN MARKETING - STROUD"},
    {label:"7677 - DFF WESTERN PETROLEUM-ROCHESTE", value:"7677 - DFF WESTERN PETROLEUM-ROCHESTE"},
    {label:"7678 - DFF WESTERN PETROLEUM-RICE LAK", value:"7678 - DFF WESTERN PETROLEUM-RICE LAK"},
    {label:"7681 - DFF WESTERN PETROL-MAPLE GROVE", value:"7681 - DFF WESTERN PETROL-MAPLE GROVE"},
    {label:"7682 - DFF WESTERN PETRO-S SAINT PAUL", value:"7682 - DFF WESTERN PETRO-S SAINT PAUL"},
    {label:"7683 - DFF WESTERN PETROL -ALBERT LEA", value:"7683 - DFF WESTERN PETROL -ALBERT LEA"},
    {label:"7684 - DFF WESTERN PETROLEUM-MOORHEAD", value:"7684 - DFF WESTERN PETROLEUM-MOORHEAD"},
    {label:"7685 - US DFF W H BRISTOW DARLINGTON", value:"7685 - US DFF W H BRISTOW DARLINGTON"},
    {label:"7687 - DFF WINDWARD PETROLE-WESTBROOK", value:"7687 - DFF WINDWARD PETROLE-WESTBROOK"},
    {label:"7689 - DFF WINDWARD PETRO - W RUTLAND", value:"7689 - DFF WINDWARD PETRO - W RUTLAND"},
    {label:"7690 - US DFF WINDWARD MANCHESTER", value:"7690 - US DFF WINDWARD MANCHESTER"},
    {label:"7691 - DFF HASCO OIL COMPANY-MONTEBEL", value:"7691 - DFF HASCO OIL COMPANY-MONTEBEL"},
    {label:"7693 - US DFF ACCULUBE (DISTR)", value:"7693 - US DFF ACCULUBE (DISTR)"},
    {label:"7695 - DFF HARRIGAN - CEDARBURG", value:"7695 - DFF HARRIGAN - CEDARBURG"},
    {label:"7696 - US DFF HASCO OIL (DISTR)", value:"7696 - US DFF HASCO OIL (DISTR)"},
    {label:"7697 - DFF VALLEN DISTRIBUTION-MONROE", value:"7697 - DFF VALLEN DISTRIBUTION-MONROE"},
    {label:"7698 - DFF VALLEN DIST-GOLDEN VALLEY", value:"7698 - DFF VALLEN DIST-GOLDEN VALLEY"},
    {label:"7699 - DFF VALLEN DISTRIBUTIO-SEATTLE", value:"7699 - DFF VALLEN DISTRIBUTIO-SEATTLE"},
    {label:"7700 - DFF VALLEN SOUTHEAST - BELMONT", value:"7700 - DFF VALLEN SOUTHEAST - BELMONT"},
    {label:"7701 - DFF VALLEN DISTRIB - WICHITA", value:"7701 - DFF VALLEN DISTRIB - WICHITA"},
    {label:"7702 - DFF NEUCO DISTRIBUTORS-BOSTWIC", value:"7702 - DFF NEUCO DISTRIBUTORS-BOSTWIC"},
    {label:"7703 - DFF STEINER ELECTRIC", value:"7703 - DFF STEINER ELECTRIC"},
    {label:"7704 - DFF WESTERN MARKETING-SAGINAW", value:"7704 - DFF WESTERN MARKETING-SAGINAW"},
    {label:"7705 - DFF WESTERN MARKETING-MERKEL", value:"7705 - DFF WESTERN MARKETING-MERKEL"},
    {label:"7706 - DFF WESTERN MARKETING-AMARILLO", value:"7706 - DFF WESTERN MARKETING-AMARILLO"},
    {label:"7707 - DFF WESTERN MARKETING-LUBBOCK", value:"7707 - DFF WESTERN MARKETING-LUBBOCK"},
    {label:"7708 - US DFF WESTERN MARKETING-TYE", value:"7708 - US DFF WESTERN MARKETING-TYE"},
    {label:"7709 - DFF Santie Oil Co - Berkeley", value:"7709 - DFF Santie Oil Co - Berkeley"},
    {label:"7710 - DFF Santie Oil Co - Sikeston", value:"7710 - DFF Santie Oil Co - Sikeston"},
    {label:"7711 - DFF Commercial Distr Oklahoma", value:"7711 - DFF Commercial Distr Oklahoma"},
    {label:"7712 - DFF Waring Oil Co Inc - Mobile", value:"7712 - DFF Waring Oil Co Inc - Mobile"},
    {label:"7713 - DFF Offen Petroelum Inc Comm C", value:"7713 - DFF Offen Petroelum Inc Comm C"},
    {label:"7714 - DFF Commercial Distr - Denton", value:"7714 - DFF Commercial Distr - Denton"},
    {label:"7715 - DFF Commercial Distr Little R", value:"7715 - DFF Commercial Distr Little R"},
    {label:"7716 - DFF Commercial Distr Arlington", value:"7716 - DFF Commercial Distr Arlington"},
    {label:"7717 - DFF Commercial Distr - Lubbock", value:"7717 - DFF Commercial Distr - Lubbock"},
    {label:"7718 - DFF SC Fuels Yuma", value:"7718 - DFF SC Fuels Yuma"},
    {label:"7719 - DFF APOLLO OIL - LOUISVILLE", value:"7719 - DFF APOLLO OIL - LOUISVILLE"},
    {label:"7720 - DFF SUPERIOR PETROLEUM OIL", value:"7720 - DFF SUPERIOR PETROLEUM OIL"},
    {label:"7721 - DFF KP SUPPLY       ", value:"7721 - DFF KP SUPPLY       "},
    {label:"7723 - DFF DENNIS K BURKE INC", value:"7723 - DFF DENNIS K BURKE INC"},
    {label:"7724 - DFF ARNOLD OIL - TAUNTON", value:"7724 - DFF ARNOLD OIL - TAUNTON"},
    {label:"7726 - DFF HUNTER OIL COMPANY INC", value:"7726 - DFF HUNTER OIL COMPANY INC"},
    {label:"7727 - US DFF COREY OIL LTD", value:"7727 - US DFF COREY OIL LTD"},
    {label:"7728 - US DFF Western Petroleum (JM O", value:"7728 - US DFF Western Petroleum (JM O"},
    {label:"7729 - US DFF AMERICAN LUBE SUPPLY", value:"7729 - US DFF AMERICAN LUBE SUPPLY"},
    {label:"7730 - US DFF Maxum DBA Thomas", value:"7730 - US DFF Maxum DBA Thomas"},
    {label:"7731 - DFF MAXUM DBA THOMAS ST GEORGE", value:"7731 - DFF MAXUM DBA THOMAS ST GEORGE"},
    {label:"7733 - US DFF COREY OIL LTD", value:"7733 - US DFF COREY OIL LTD"},
    {label:"9008 - PT INTCO LHCVC (Lubes Direct D", value:"9008 - PT INTCO LHCVC (Lubes Direct D"},
    {label:"9009 - FR Interco and Consignment", value:"9009 - FR Interco and Consignment"},
    {label:"9010 - BE Interco and Consignment", value:"9010 - BE Interco and Consignment"},
    {label:"9011 - NL Interco and Consignment", value:"9011 - NL Interco and Consignment"},
    {label:"9012 - IT Interco and Consignment", value:"9012 - IT Interco and Consignment"},
    {label:"9013 - IE Interco and Consignment", value:"9013 - IE Interco and Consignment"},
    {label:"9014 - GB Interco and Consignment", value:"9014 - GB Interco and Consignment"},
    {label:"9015 - ES BP OIL España S.A.U", value:"9015 - ES BP OIL España S.A.U"},
    {label:"9016 - GI Interco and Consignment", value:"9016 - GI Interco and Consignment"},
    {label:"9017 - DE Interco and Consignment", value:"9017 - DE Interco and Consignment"},
    {label:"9401 - DK Interco and Consignment", value:"9401 - DK Interco and Consignment"},
    {label:"9402 - FI Interco and Consignment", value:"9402 - FI Interco and Consignment"},
    {label:"9403 - NO Interco and Consignment", value:"9403 - NO Interco and Consignment"},
    {label:"9404 - SE Interco and Consignment", value:"9404 - SE Interco and Consignment"},
    {label:"9501 - USA Virtual Plant", value:"9501 - USA Virtual Plant"},
    {label:"9502 - Canada virtual plant", value:"9502 - Canada virtual plant"},
    {label:"9504 - CCSA virtual plant-Wilmington", value:"9504 - CCSA virtual plant-Wilmington"},
    {label:"DE0J - BP Europa SE (LU)", value:"DE0J - BP Europa SE (LU)"},
    {label:"DE2K - Castrol Ind Serv (LU)", value:"DE2K - Castrol Ind Serv (LU)"},
    {label:"DKH8 - DK BP Office Plant", value:"DKH8 - DK BP Office Plant"},
    {label:"FI01 - FI BP Office Plant", value:"FI01 - FI BP Office Plant"},
    {label:"MX03 - Castrol Mexico, S.A. DE C.V.", value:"MX03 - Castrol Mexico, S.A. DE C.V."},
    {label:"MX04 - MES Tecnologia EN Servicios", value:"MX04 - MES Tecnologia EN Servicios"},
    {label:"NO10 - NO BP Office Plant", value:"NO10 - NO BP Office Plant"},
    {label:"SE10 - SE BP Office Plant", value:"SE10 - SE BP Office Plant"}
]

export const opt_distribution_channel=[
    {label:"10 (Offshore)", value:"10 (Offshore)"},
    {label:"11 (Power)", value:"11 (Power)"}

]

export const opt_be_zvat=[
    {label:"1-Fully Taxable", value:"1 - Fully Taxable"},
    {label:"2-Army/Diplomats/NATO", value:"2 - Army/Diplomats/NATO"},
    {label:"3-Supplies BPMLI", value:"3 - Supplies BPMLI"},
    {label:"4-Intra LE/Fisc. Unity", value:"4 - Intra LE/Fisc. Unity"},
    {label:"5-9-Exemptions", value:"5-9 - Exemptions"}
]

export const opt_be_zeco=[
    {label:"1-Fully Taxable", value:"1 - Fully Taxable"},
    {label:"2-Exempt", value:"2 - Exempt"},
    {label:"3-Export by Customer", value:"3 - Export by Customer"},
    {label:"7-Special Customers", value:"7 - Special Customers"}
]

// Detecta (Hydraulic UOA)
// Specialist Stern Tube (Standard)
// Stern Tube (BV & NK)
// Caremax Stern Tube (with Ferrography)
// Predict (Machinery Condition Monitoring)
// Asphaltenes
// Super
export const opt_sda_samples = [
    { label: "SDA basic (Fuel & System)", value: "SDA basic (Fuel & System)" },
    { label: "SDA Cylinders", value: "SDA Cylinders" },
    { label: "SDA Troubleshooting", value: "SDA Troubleshooting" }
]

export const opt_service_desc=[
    {label:"Basic Sample", value:"Basic"},
    {label:"Detecta (Hydraulic UOA)", value:"Detecta (Hydraulic UOA)"},
    {label:"Specialist Stern Tube (Standard)", value:"Specialist Stern Tube (Standard)"},
    {label:"Stern Tube (BV & NK)", value:"Stern Tube (BV & NK)"},
    {label:"Caremax Stern Tube (with Ferrography)", value:"Caremax Stern Tube (with Ferrography)"},
    {label:"Predict (Machinery Condition Monitoring)", value:"Predict (Machinery Condition Monitoring)"},
    {label:"Asphaltenes", value:"Asphaltenes"},
    {label:"Super", value:"Super"},
]

export const opt_uoa_invoicing_freq=[
    {label:"Monthly", value:"Monthly"},
    {label:"Quarterly", value:"Quarterly"},
    {label:"Half Yearly", value:"Half Yearly"},
    {label:"Yearly", value:"Yearly"}
]
export const opt_it_zmot=[
    {label:"1-Fully Taxable", value:"1 - Fully Taxable"},
    {label:"2-Exempt", value:"2 - Exempt"},
    {label:"3-MOT inc List Price", value:"3 - MOT inc List Price"}
]

export const opt_country=[
    {label:"AD - Andorra", value:"AD - Andorra"},
    {label:"AE - Utd.Arab Emir", value:"AE - Utd.Arab Emir"},
    {label:"AF - Afghanistan", value:"AF - Afghanistan"},
    {label:"AG - Antigua/Barbuda", value:"AG - Antigua/Barbuda"},
    {label:"AI - Anguilla", value:"AI - Anguilla"},
    {label:"AL - Albania", value:"AL - Albania"},
    {label:"AM - Armenia", value:"AM - Armenia"},
    {label:"AN - Dutch Antilles", value:"AN - Dutch Antilles"},
    {label:"AO - Angola", value:"AO - Angola"},
    {label:"AQ - Antarctica", value:"AQ - Antarctica"},
    {label:"AR - Argentina", value:"AR - Argentina"},
    {label:"AS - Samoa, America", value:"AS - Samoa, America"},
    {label:"AT - Austria", value:"AT - Austria"},
    {label:"AU - Australia", value:"AU - Australia"},
    {label:"AW - Aruba", value:"AW - Aruba"},
    {label:"AX - Aland Islands", value:"AX - Aland Islands"},
    {label:"AZ - Azerbaijan", value:"AZ - Azerbaijan"},
    {label:"BA - Bosnia-Herz.", value:"BA - Bosnia-Herz."},
    {label:"BB - Barbados", value:"BB - Barbados"},
    {label:"BD - Bangladesh", value:"BD - Bangladesh"},
    {label:"BE - Belgium", value:"BE - Belgium"},
    {label:"BF - Burkina Faso", value:"BF - Burkina Faso"},
    {label:"BG - Bulgaria", value:"BG - Bulgaria"},
    {label:"BH - Bahrain", value:"BH - Bahrain"},
    {label:"BI - Burundi", value:"BI - Burundi"},
    {label:"BJ - Benin", value:"BJ - Benin"},
    {label:"BL - St Barthélemy", value:"BL - St Barthélemy"},
    {label:"BM - Bermuda", value:"BM - Bermuda"},
    {label:"BN - Brunei Daruss.", value:"BN - Brunei Daruss."},
    {label:"BO - Bolivia", value:"BO - Bolivia"},
    {label:"BQ - Bonaire, Saba", value:"BQ - Bonaire, Saba"},
    {label:"BR - Brazil", value:"BR - Brazil"},
    {label:"BS - Bahamas", value:"BS - Bahamas"},
    {label:"BT - Bhutan", value:"BT - Bhutan"},
    {label:"BV - Bouvet Islands", value:"BV - Bouvet Islands"},
    {label:"BW - Botswana", value:"BW - Botswana"},
    {label:"BY - Belarus", value:"BY - Belarus"},
    {label:"BZ - Belize", value:"BZ - Belize"},
    {label:"CA - Canada", value:"CA - Canada"},
    {label:"CC - Cocos Islands", value:"CC - Cocos Islands"},
    {label:"CD - Congo(DRC)", value:"CD - Congo(DRC)"},
    {label:"CF - Central Afr.Rep", value:"CF - Central Afr.Rep"},
    {label:"CG - Congo", value:"CG - Congo"},
    {label:"CH - Switzerland", value:"CH - Switzerland"},
    {label:"CI - Cote D'Ivoire", value:"CI - Cote D'Ivoire"},
    {label:"CK - Cook Islands", value:"CK - Cook Islands"},
    {label:"CL - Chile", value:"CL - Chile"},
    {label:"CM - Cameroon", value:"CM - Cameroon"},
    {label:"CN - China", value:"CN - China"},
    {label:"CO - Colombia", value:"CO - Colombia"},
    {label:"CR - Costa Rica", value:"CR - Costa Rica"},
    {label:"CT - Turkish Cyprus", value:"CT - Turkish Cyprus"},
    {label:"CU - Cuba", value:"CU - Cuba"},
    {label:"CV - Cape Verde", value:"CV - Cape Verde"},
    {label:"CW - Curaçao", value:"CW - Curaçao"},
    {label:"CX - Christmas Islnd", value:"CX - Christmas Islnd"},
    {label:"CY - Cyprus", value:"CY - Cyprus"},
    {label:"CZ - Czech Republic", value:"CZ - Czech Republic"},
    {label:"DE - Germany", value:"DE - Germany"},
    {label:"DJ - Djibouti", value:"DJ - Djibouti"},
    {label:"DK - Denmark", value:"DK - Denmark"},
    {label:"DM - Dominica", value:"DM - Dominica"},
    {label:"DO - Dominican Rep.", value:"DO - Dominican Rep."},
    {label:"DZ - Algeria", value:"DZ - Algeria"},
    {label:"EC - Ecuador", value:"EC - Ecuador"},
    {label:"EE - Estonia", value:"EE - Estonia"},
    {label:"EG - Egypt", value:"EG - Egypt"},
    {label:"EH - Western Sahara", value:"EH - Western Sahara"},
    {label:"ER - Eritrea", value:"ER - Eritrea"},
    {label:"ES - Spain", value:"ES - Spain"},
    {label:"ET - Ethiopia", value:"ET - Ethiopia"},
    {label:"EU - Europe", value:"EU - Europe"},
    {label:"FI - Finland", value:"FI - Finland"},
    {label:"FJ - Fiji", value:"FJ - Fiji"},
    {label:"FK - Falkland Islnds", value:"FK - Falkland Islnds"},
    {label:"FM - Micronesia", value:"FM - Micronesia"},
    {label:"FO - Faroe Islands", value:"FO - Faroe Islands"},
    {label:"FR - France", value:"FR - France"},
    {label:"GA - Gabon", value:"GA - Gabon"},
    {label:"GB - United Kingdom", value:"GB - United Kingdom"},
    {label:"GD - Grenada", value:"GD - Grenada"},
    {label:"GE - Georgia", value:"GE - Georgia"},
    {label:"GF - French Guiana", value:"GF - French Guiana"},
    {label:"GG - Guernsey", value:"GG - Guernsey"},
    {label:"GH - Ghana", value:"GH - Ghana"},
    {label:"GI - Gibraltar", value:"GI - Gibraltar"},
    {label:"GL - Greenland", value:"GL - Greenland"},
    {label:"GM - Gambia", value:"GM - Gambia"},
    {label:"GN - Guinea", value:"GN - Guinea"},
    {label:"GP - Guadeloupe", value:"GP - Guadeloupe"},
    {label:"GQ - Equatorial Guin", value:"GQ - Equatorial Guin"},
    {label:"GR - Greece", value:"GR - Greece"},
    {label:"GS - South Georgia", value:"GS - South Georgia"},
    {label:"GT - Guatemala", value:"GT - Guatemala"},
    {label:"GU - Guam", value:"GU - Guam"},
    {label:"GW - Guinea-Bissau", value:"GW - Guinea-Bissau"},
    {label:"GY - Guyana", value:"GY - Guyana"},
    {label:"HK - Hong Kong", value:"HK - Hong Kong"},
    {label:"HM - Heard/McDon.Isl", value:"HM - Heard/McDon.Isl"},
    {label:"HN - Honduras", value:"HN - Honduras"},
    {label:"HR - Croatia", value:"HR - Croatia"},
    {label:"HT - Haiti", value:"HT - Haiti"},
    {label:"HU - Hungary", value:"HU - Hungary"},
    {label:"ID - Indonesia", value:"ID - Indonesia"},
    {label:"IE - Ireland", value:"IE - Ireland"},
    {label:"IL - Israel", value:"IL - Israel"},
    {label:"IM - Isle of Man", value:"IM - Isle of Man"},
    {label:"IN - India", value:"IN - India"},
    {label:"IO - Brit.Ind.Oc.Ter", value:"IO - Brit.Ind.Oc.Ter"},
    {label:"IQ - Iraq", value:"IQ - Iraq"},
    {label:"IR - Iran", value:"IR - Iran"},
    {label:"IS - Iceland", value:"IS - Iceland"},
    {label:"IT - Italy", value:"IT - Italy"},
    {label:"JE - Jersey", value:"JE - Jersey"},
    {label:"JM - Jamaica", value:"JM - Jamaica"},
    {label:"JO - Jordan", value:"JO - Jordan"},
    {label:"JP - Japan", value:"JP - Japan"},
    {label:"KE - Kenya", value:"KE - Kenya"},
    {label:"KG - Kyrgyzstan", value:"KG - Kyrgyzstan"},
    {label:"KH - Cambodia", value:"KH - Cambodia"},
    {label:"KI - Kiribati", value:"KI - Kiribati"},
    {label:"KM - Comoros", value:"KM - Comoros"},
    {label:"KN - St Kitts&Nevis", value:"KN - St Kitts&Nevis"},
    {label:"KP - North Korea", value:"KP - North Korea"},
    {label:"KR - South Korea", value:"KR - South Korea"},
    {label:"KW - Kuwait", value:"KW - Kuwait"},
    {label:"KY - Cayman Islands", value:"KY - Cayman Islands"},
    {label:"KZ - Kazakhstan", value:"KZ - Kazakhstan"},
    {label:"LA - Laos", value:"LA - Laos"},
    {label:"LB - Lebanon", value:"LB - Lebanon"},
    {label:"LC - Saint Lucia", value:"LC - Saint Lucia"},
    {label:"LDB - Land Based", value:"LDB - Land Based"},
    {label:"LI - Liechtenstein", value:"LI - Liechtenstein"},
    {label:"LK - Sri Lanka", value:"LK - Sri Lanka"},
    {label:"LR - Liberia", value:"LR - Liberia"},
    {label:"LS - Lesotho", value:"LS - Lesotho"},
    {label:"LT - Lithuania", value:"LT - Lithuania"},
    {label:"LU - Luxembourg", value:"LU - Luxembourg"},
    {label:"LV - Latvia", value:"LV - Latvia"},
    {label:"LY - Libya", value:"LY - Libya"},
    {label:"MA - Morocco", value:"MA - Morocco"},
    {label:"MC - Monaco", value:"MC - Monaco"},
    {label:"MD - Moldova", value:"MD - Moldova"},
    {label:"ME - Montenegro", value:"ME - Montenegro"},
    {label:"MF - Saint Martin", value:"MF - Saint Martin"},
    {label:"MG - Madagascar", value:"MG - Madagascar"},
    {label:"MH - Marshall Islnds", value:"MH - Marshall Islnds"},
    {label:"MK - Macedonia", value:"MK - Macedonia"},
    {label:"ML - Mali", value:"ML - Mali"},
    {label:"MM - Myanmar", value:"MM - Myanmar"},
    {label:"MN - Mongolia", value:"MN - Mongolia"},
    {label:"MO - Macau", value:"MO - Macau"},
    {label:"MP - N.Mariana Isl.", value:"MP - N.Mariana Isl."},
    {label:"MQ - Martinique", value:"MQ - Martinique"},
    {label:"MR - Mauritania", value:"MR - Mauritania"},
    {label:"MS - Montserrat", value:"MS - Montserrat"},
    {label:"MT - Malta", value:"MT - Malta"},
    {label:"MU - Mauritius", value:"MU - Mauritius"},
    {label:"MV - Maldives", value:"MV - Maldives"},
    {label:"MW - Malawi", value:"MW - Malawi"},
    {label:"MX - Mexico", value:"MX - Mexico"},
    {label:"MY - Malaysia", value:"MY - Malaysia"},
    {label:"MZ - Mozambique", value:"MZ - Mozambique"},
    {label:"NA - Namibia", value:"NA - Namibia"},
    {label:"NC - New Caledonia", value:"NC - New Caledonia"},
    {label:"NDB - Not provided", value:"NDB - Not provided"},
    {label:"NE - Niger", value:"NE - Niger"},
    {label:"NF - Norfolk Island", value:"NF - Norfolk Island"},
    {label:"NG - Nigeria", value:"NG - Nigeria"},
    {label:"NI - Nicaragua", value:"NI - Nicaragua"},
    {label:"NL - Netherlands", value:"NL - Netherlands"},
    {label:"NO - Norway", value:"NO - Norway"},
    {label:"NP - Nepal", value:"NP - Nepal"},
    {label:"NR - Nauru", value:"NR - Nauru"},
    {label:"NT - NATO", value:"NT - NATO"},
    {label:"NU - Niue", value:"NU - Niue"},
    {label:"NZ - New Zealand", value:"NZ - New Zealand"},
    {label:"OA - Other Africa", value:"OA - Other Africa"},
    {label:"OM - Oman", value:"OM - Oman"},
    {label:"OR - Orange", value:"OR - Orange"},
    {label:"PA - Panama", value:"PA - Panama"},
    {label:"PE - Peru", value:"PE - Peru"},
    {label:"PF - French Polynes.", value:"PF - French Polynes."},
    {label:"PG - Pap. New Guinea", value:"PG - Pap. New Guinea"},
    {label:"PH - Philippines", value:"PH - Philippines"},
    {label:"PK - Pakistan", value:"PK - Pakistan"},
    {label:"PL - Poland", value:"PL - Poland"},
    {label:"PM - St.Pier,Miquel.", value:"PM - St.Pier,Miquel."},
    {label:"PN - Pitcairn Islnds", value:"PN - Pitcairn Islnds"},
    {label:"PR - Puerto Rico", value:"PR - Puerto Rico"},
    {label:"PS - Palestine", value:"PS - Palestine"},
    {label:"PT - Portugal", value:"PT - Portugal"},
    {label:"PW - Palau", value:"PW - Palau"},
    {label:"PY - Paraguay", value:"PY - Paraguay"},
    {label:"QA - Qatar", value:"QA - Qatar"},
    {label:"R1 - Russia ROE", value:"R1 - Russia ROE"},
    {label:"RE - Reunion", value:"RE - Reunion"},
    {label:"RO - Romania", value:"RO - Romania"},
    {label:"RS - Serbia", value:"RS - Serbia"},
    {label:"RU - Russian Fed.", value:"RU - Russian Fed."},
    {label:"RW - Rwanda", value:"RW - Rwanda"},
    {label:"SA - Saudi Arabia", value:"SA - Saudi Arabia"},
    {label:"SB - Solomon Islands", value:"SB - Solomon Islands"},
    {label:"SC - Seychelles", value:"SC - Seychelles"},
    {label:"SD - Sudan", value:"SD - Sudan"},
    {label:"SE - Sweden", value:"SE - Sweden"},
    {label:"SG - Singapore", value:"SG - Singapore"},
    {label:"SH - Saint Helena", value:"SH - Saint Helena"},
    {label:"SHP - SH CNTRY", value:"SHP - SH CNTRY"},
    {label:"SI - Slovenia", value:"SI - Slovenia"},
    {label:"SJ - Svalbard", value:"SJ - Svalbard"},
    {label:"SK - Slovakia", value:"SK - Slovakia"},
    {label:"SL - Sierra Leone", value:"SL - Sierra Leone"},
    {label:"SLD - Sold to country", value:"SLD - Sold to country"},
    {label:"SM - San Marino", value:"SM - San Marino"},
    {label:"SN - Senegal", value:"SN - Senegal"},
    {label:"SO - Somalia", value:"SO - Somalia"},
    {label:"SR - Suriname", value:"SR - Suriname"},
    {label:"SS - South Sudan", value:"SS - South Sudan"},
    {label:"ST - S.Tome,Principe", value:"ST - S.Tome,Principe"},
    {label:"SV - El Salvador", value:"SV - El Salvador"},
    {label:"SX - Sint Maarten", value:"SX - Sint Maarten"},
    {label:"SY - Syria", value:"SY - Syria"},
    {label:"SZ - Eswatini", value:"SZ - Eswatini"},
    {label:"T1 - Turkey ROW", value:"T1 - Turkey ROW"},
    {label:"TC - Turks & Caicos", value:"TC - Turks & Caicos"},
    {label:"TD - Chad", value:"TD - Chad"},
    {label:"TF - French S.Territ", value:"TF - French S.Territ"},
    {label:"TG - Togo", value:"TG - Togo"},
    {label:"TH - Thailand", value:"TH - Thailand"},
    {label:"TJ - Tajikistan", value:"TJ - Tajikistan"},
    {label:"TK - Tokelau", value:"TK - Tokelau"},
    {label:"TL - Timor-Leste", value:"TL - Timor-Leste"},
    {label:"TM - Turkmenistan", value:"TM - Turkmenistan"},
    {label:"TN - Tunisia", value:"TN - Tunisia"},
    {label:"TO - Tonga", value:"TO - Tonga"},
    {label:"TP - East Timor", value:"TP - East Timor"},
    {label:"TR - Turkey", value:"TR - Turkey"},
    {label:"TT - Trinidad,Tobago", value:"TT - Trinidad,Tobago"},
    {label:"TV - Tuvalu", value:"TV - Tuvalu"},
    {label:"TW - Taiwan", value:"TW - Taiwan"},
    {label:"TZ - Tanzania", value:"TZ - Tanzania"},
    {label:"UA - Ukraine", value:"UA - Ukraine"},
    {label:"UG - Uganda", value:"UG - Uganda"},
    {label:"UM - Minor Outl.Isl.", value:"UM - Minor Outl.Isl."},
    {label:"UN - United Nations", value:"UN - United Nations"},
    {label:"US - United States", value:"US - United States"},
    {label:"UY - Uruguay", value:"UY - Uruguay"},
    {label:"UZ - Uzbekistan", value:"UZ - Uzbekistan"},
    {label:"VA - Vatican City", value:"VA - Vatican City"},
    {label:"VC - St. Vincent", value:"VC - St. Vincent"},
    {label:"VE - Venezuela", value:"VE - Venezuela"},
    {label:"VG - Brit.Virgin Is.", value:"VG - Brit.Virgin Is."},
    {label:"VI - Amer.Virgin Is.", value:"VI - Amer.Virgin Is."},
    {label:"VN - Vietnam", value:"VN - Vietnam"},
    {label:"VU - Vanuatu", value:"VU - Vanuatu"},
    {label:"WF - Wallis,Futuna", value:"WF - Wallis,Futuna"},
    {label:"WO - Rest of World", value:"WO - Rest of World"},
    {label:"WS - Samoa", value:"WS - Samoa"},
    {label:"X1 - (Do not use)", value:"X1 - (Do not use)"},
    {label:"XK - Kosovo", value:"XK - Kosovo"},
    {label:"XV - Northern Cyprus", value:"XV - Northern Cyprus"},
    {label:"YE - Yemen", value:"YE - Yemen"},
    {label:"YT - Mayotte", value:"YT - Mayotte"},
    {label:"YU - Yugoslavia", value:"YU - Yugoslavia"},
    {label:"ZA - South Africa", value:"ZA - South Africa"},
    {label:"ZM - Zambia", value:"ZM - Zambia"},
    {label:"ZW - Zimbabwe", value:"ZW - Zimbabwe"},
    {label:"ZZ - Pricing Country", value:"ZZ - Pricing Country"} 
]

export const opt_countrysalesregionmapping={
    "AD - Andorra": "Europe and Africa",
    "AL - Albania": "Europe and Africa",
    "AM - Armenia": "Europe and Africa",
    "AN - Dutch Antilles": "Europe and Africa",
    "AT - Austria": "Europe and Africa",
    "AX - Aland Islands": "Europe and Africa",
    "AZ - Azerbaijan": "Europe and Africa",
    "BA - Bosnia-Herz.": "Europe and Africa",
    "BE - Belgium": "Europe and Africa",
    "BG - Bulgaria": "Europe and Africa",
    "BY - Belarus": "Europe and Africa",
    "CH - Switzerland": "Europe and Africa",
    "CT - Turkish Cyprus": "Europe and Africa",
    "CY - Cyprus": "Europe and Africa",
    "CZ - Czech Republic": "Europe and Africa",
    "DE - Germany": "Europe and Africa",
    "DK - Denmark": "Europe and Africa",
    "EE - Estonia": "Europe and Africa",
    "ES - Spain": "Europe and Africa",
    "EU - Europe": "Europe and Africa",
    "FI - Finland": "Europe and Africa",
    "FO - Faroe Islands": "Europe and Africa",
    "FR - France": "Europe and Africa",
    "GB - United Kingdom": "Europe and Africa",
    "GE - Georgia": "Europe and Africa",
    "GG - Guernsey": "Europe and Africa",
    "GI - Gibraltar": "Europe and Africa",
    "GR - Greece": "Europe and Africa",
    "HR - Croatia": "Europe and Africa",
    "HU - Hungary": "Europe and Africa",
    "IE - Ireland": "Europe and Africa",
    "IM - Isle of Man": "Europe and Africa",
    "IS - Iceland": "Europe and Africa",
    "IT - Italy": "Europe and Africa",
    "JE - Jersey": "Europe and Africa",
    "LI - Liechtenstein": "Europe and Africa",
    "LT - Lithuania": "Europe and Africa",
    "LU - Luxembourg": "Europe and Africa",
    "LV - Latvia": "Europe and Africa",
    "MC - Monaco": "Europe and Africa",
    "MD - Moldova": "Europe and Africa",
    "ME - Montenegro": "Europe and Africa",
    "MK - Macedonia": "Europe and Africa",
    "MT - Malta": "Europe and Africa",
    "NL - Netherlands": "Europe and Africa",
    "NO - Norway": "Europe and Africa",
    "PL - Poland": "Europe and Africa",
    "PT - Portugal": "Europe and Africa",
    "RO - Romania": "Europe and Africa",
    "RS - Serbia": "Europe and Africa",
    "RU - Russian Fed.": "Europe and Africa",
    "R1 - Russia ROE": "Europe and Africa",
    "SE - Sweden": "Europe and Africa",
    "SI - Slovenia": "Europe and Africa",
    "SJ - Svalbard": "Europe and Africa",
    "SK - Slovakia": "Europe and Africa",
    "SM - San Marino": "Europe and Africa",
    "UA - Ukraine": "Europe and Africa",
    "VA - Vatican City": "Europe and Africa",
    "XK - Kosovo": "Europe and Africa",
    "XV - Northern Cyprus": "Europe and Africa",
    "YU - Yugoslavia": "Europe and Africa",
    "AO - Angola": "Europe and Africa",
    "BF - Burkina Faso": "Europe and Africa",
    "BI - Burundi": "Europe and Africa",
    "BJ - Benin": "Europe and Africa",
    "BW - Botswana": "Europe and Africa",
    "CD - Congo DRC": "Europe and Africa",
    "CF - Central African Republic": "Europe and Africa",
    "CG - Congo": "Europe and Africa",
    "CI - Cote D Ivoire": "Europe and Africa",
    "CM - Cameroon": "Europe and Africa",
    "CV - Cape Verde": "Europe and Africa",
    "DJ - Djibouti": "Europe and Africa",
    "DZ - Algeria": "Europe and Africa",
    "EG - Egypt": "Europe and Africa",
    "EH - Western Sahara": "Europe and Africa",
    "ER - Eritrea": "Europe and Africa",
    "ET - Ethiopia": "Europe and Africa",
    "GA - Gabon": "Europe and Africa",
    "GH - Ghana": "Europe and Africa",
    "GM - Gambia": "Europe and Africa",
    "GN - Guinea": "Europe and Africa",
    "GQ - Equatorial Guinea": "Europe and Africa",
    "GW - Guinea-Bissau": "Europe and Africa",
    "KE - Kenya": "Europe and Africa",
    "KM - Comoros": "Europe and Africa",
    "LR - Liberia": "Europe and Africa",
    "LS - Lesotho": "Europe and Africa",
    "LY - Libya": "Europe and Africa",
    "MA - Morocco": "Europe and Africa",
    "MG - Madagascar": "Europe and Africa",
    "ML - Mali": "Europe and Africa",
    "MR - Mauritania": "Europe and Africa",
    "MU - Mauritius": "Europe and Africa",
    "MW - Malawi": "Europe and Africa",
    "MZ - Mozambique": "Europe and Africa",
    "NA - Namibia": "Europe and Africa",
    "NE - Niger": "Europe and Africa",
    "NG - Nigeria": "Europe and Africa",
    "OA - Other Africa": "Europe and Africa",
    "RE - Reunion": "Europe and Africa",
    "RW - Rwanda": "Europe and Africa",
    "SC - Seychelles": "Europe and Africa",
    "SD - Sudan": "Europe and Africa",
    "SL - Sierra Leone": "Europe and Africa",
    "SN - Senegal": "Europe and Africa",
    "SO - Somalia": "Europe and Africa",
    "SS - South Sudan": "Europe and Africa",
    "ST - Sao Tome & Principe": "Europe and Africa",
    "SZ - Eswatini": "Europe and Africa",
    "TD - Chad": "Europe and Africa",
    "TG - Togo": "Europe and Africa",
    "TN - Tunisia": "Europe and Africa",
    "TZ - Tanzania": "Europe and Africa",
    "UG - Uganda": "Europe and Africa",
    "YT - Mayotte": "Europe and Africa",
    "ZA - South Africa": "Europe and Africa",
    "ZM - Zambia": "Europe and Africa",
    "ZW - Zimbabwe": "Europe and Africa",
    "AG - Antigua & Barbuda": "Americas",
    "AI - Anguilla": "Americas",
    "AR - Argentina": "Americas",
    "AW - Aruba": "Americas",
    "BB - Barbados": "Americas",
    "BL - St Barthelemy": "Americas",
    "BM - Bermuda": "Americas",
    "BO - Bolivia": "Americas",
    "BQ - Bonaire, Saba": "Americas",
    "BR - Brazil": "Americas",
    "BS - Bahamas": "Americas",
    "BZ - Belize": "Americas",
    "CA - Canada": "Americas",
    "CL - Chile": "Americas",
    "CO - Colombia": "Americas",
    "CR - Costa Rica": "Americas",
    "CU - Cuba": "Americas",
    "CW - Curacao": "Americas",
    "DM - Dominica": "Americas",
    "DO - Dominican Republic": "Americas",
    "EC - Ecuador": "Americas",
    "FK - Falkland Islands": "Americas",
    "GD - Grenada": "Americas",
    "GF - French Guiana": "Americas",
    "GL - Greenland": "Americas",
    "GP - Guadeloupe": "Americas",
    "GT - Guatemala": "Americas",
    "GY - Guyana": "Americas",
    "HN - Honduras": "Americas",
    "HT - Haiti": "Americas",
    "JM - Jamaica": "Americas",
    "KN - St Kitts & Nevis": "Americas",
    "KY - Cayman Islands": "Americas",
    "LC - Saint Lucia": "Americas",
    "MQ - Martinique": "Americas",
    "MS - Montserrat": "Americas",
    "MX - Mexico": "Americas",
    "NI - Nicaragua": "Americas",
    "PA - Panama": "Americas",
    "PE - Peru": "Americas",
    "PM - St Pierre & Miquelon": "Americas",
    "PR - Puerto Rico": "Americas",
    "PY - Paraguay": "Americas",
    "SR - Suriname": "Americas",
    "SV - El Salvador": "Americas",
    "TC - Turks & Caicos": "Americas",
    "TT - Trinidad & Tobago": "Americas",
    "US - United States": "Americas",
    "UY - Uruguay": "Americas",
    "VC - St Vincent": "Americas",
    "VE - Venezuela": "Americas",
    "VG - British Virgin Islands": "Americas",
    "VI - American Virgin Islands": "Americas",
    "AE - United Arab Emirates": "AsPac",
    "AF - Afghanistan": "AsPac",
    "AQ - Antarctica": "AsPac",
    "AS - American Samoa": "AsPac",
    "AU - Australia": "AsPac",
    "BD - Bangladesh": "AsPac",
    "BH - Bahrain": "AsPac",
    "BN - Brunei": "AsPac",
    "BT - Bhutan": "AsPac",
    "BV - Bouvet Island": "AsPac",
    "CC - Cocos Islands": "AsPac",
    "CN - China": "AsPac",
    "CX - Christmas Island": "AsPac",
    "FJ - Fiji": "AsPac",
    "FM - Micronesia": "AsPac",
    "GU - Guam": "AsPac",
    "HK - Hong Kong": "AsPac",
    "HM - Heard & McDonald Islands": "AsPac",
    "ID - Indonesia": "AsPac",
    "IL - Israel": "AsPac",
    "IN - India": "AsPac",
    "IO - British Indian Ocean Territory": "AsPac",
    "IQ - Iraq": "AsPac",
    "IR - Iran": "AsPac",
    "JO - Jordan": "AsPac",
    "JP - Japan": "AsPac",
    "KG - Kyrgyzstan": "AsPac",
    "KH - Cambodia": "AsPac",
    "KI - Kiribati": "AsPac",
    "KP - North Korea": "AsPac",
    "KR - South Korea": "AsPac",
    "KW - Kuwait": "AsPac",
    "KZ - Kazakhstan": "AsPac",
    "LA - Laos": "AsPac",
    "LB - Lebanon": "AsPac",
    "LK - Sri Lanka": "AsPac",
    "LDB - Land Based": "AsPac",
    "MM - Myanmar": "AsPac",
    "MN - Mongolia": "AsPac",
    "MO - Macau": "AsPac",
    "MP - Northern Mariana Islands": "AsPac",
    "MV - Maldives": "AsPac",
    "MY - Malaysia": "AsPac",
    "NC - New Caledonia": "AsPac",
    "NF - Norfolk Island": "AsPac",
    "NP - Nepal": "AsPac",
    "NR - Nauru": "AsPac",
    "NT - NATO": "AsPac",
    "NU - Niue": "AsPac",
    "NZ - New Zealand": "AsPac",
    "OM - Oman": "AsPac",
    "OR - Orange": "AsPac",
    "PF - French Polynesia": "AsPac",
    "PG - Papua New Guinea": "AsPac",
    "PH - Philippines": "AsPac",
    "PK - Pakistan": "AsPac",
    "PS - Palestine": "AsPac",
    "PW - Palau": "AsPac",
    "QA - Qatar": "AsPac",
    "SA - Saudi Arabia": "AsPac",
    "SB - Solomon Islands": "AsPac",
    "SG - Singapore": "AsPac",
    "SH - Saint Helena": "AsPac",
    "SHP - SH Country": "AsPac",
    "SY - Syria": "AsPac",
    "T1 - Turkey ROW": "AsPac",
    "TF - French Southern Territories": "AsPac",
    "TH - Thailand": "AsPac",
    "TJ - Tajikistan": "AsPac",
    "TK - Tokelau": "AsPac",
    "TL - Timor-Leste": "AsPac",
    "TM - Turkmenistan": "AsPac",
    "TO - Tonga": "AsPac",
    "TP - East Timor": "AsPac",
    "TR - Turkey": "AsPac",
    "TV - Tuvalu": "AsPac",
    "TW - Taiwan": "AsPac",
    "UZ - Uzbekistan": "AsPac",
    "VN - Vietnam": "AsPac",
    "VU - Vanuatu": "AsPac",
    "WF - Wallis & Futuna": "AsPac",
    "WO - Rest of World": "AsPac",
    "WS - Samoa": "AsPac",
    "YE - Yemen": "AsPac"
}
export const opt_industry=[
    {label:"CENE - BP ENERGY", value:"CENE - BP ENERGY"},
    {label:"CGAP - Gas and Power", value:"CGAP - Gas and Power"}
]

export const opt_uoa_offer=[
    {label:"Ownership change(changing from one customer to another)",value:"ownershipchange"},
    {label:"Name change for existing UOA offer for vessel",value:"namechange"},
    {label:"Enddate existing UOA offer for vessel",value:"enddateexisting"},
    {label:"Changing the pricing options for the vessel specific UOA offer",value:"changingpricing"}                   
]

export const opt_energy_uoa_offer=[
    {label:"Ownership change(changing from one customer to another)",value:"ownershipchange"},
    {label:"Name change for existing UOA offer for vessel",value:"namechange"},
    {label:"Enddate existing UOA offer for vessel",value:"enddateexisting"},
    // {label:"Changing the pricing options for the vessel specific UOA offer",value:"changingpricing"}                   
]

  export const opt_casetypes=[
    {label:"UOA Old offer for newly created customer",value:"UOA Old offer for newly created customer"},
    {label:"Modifying existing UOA offer for customer",value:"Modifying existing UOA offer for customer"},
    {label:"UOA offer for new vessel",value:"UOA offer for new vessel"},
    {label:"Modify existing UOA offer for vessel",value:"Modify existing UOA offer for vessel"},
    {label:"No UOA Action Required",value:"No UOA Action Required"}
  ]

export const opt_energy_casetypes=[
    {label:"UOA offer for newly created customer",value:"UOA offer for newly created customer"},
    {label:"Modifying existing UOA offer for customer",value:"Modifying existing UOA offer for customer"},
    {label:"UOA offer for new vessel",value:"UOA offer for new vessel"},
    {label:"Modify existing UOA offer for vessel",value:"Modify existing UOA offer for vessel"},
    {label:"Other",value:"Other"}
  ]

// export const opt_casetypes=[
//     {label:"UOA Old offer for newly created customer",value:"Oldofferfornewcustomer"},
//     {label:"Modifying existing UOA offer for customer",value:"offerforexistingcustomer"},
//     {label:"UOA offer for new vessel",value:"offerfornewvessel"},
//     {label:"Modify existing UOA offer for vessel",value:"offerforexistingvessel"},
//     {label:"Other",value:"other"}
//   ]

//     export const opt_casetypes=[
//     {label:"UOA offer for newly created customer",value:"offerfornewcustomer"},
//     {label:"Modifying existing UOA offer for customer",value:"offerforexistingcustomer"},
//     {label:"UOA offer for new vessel",value:"offerfornewvessel"},
//     {label:"Modify existing UOA offer for vessel",value:"offerforexistingvessel"},
//     {label:"Other",value:"other"}
//   ]

  export const columns_Cust = [
    { field: "customerid", headerName: "customerid",maxWidth:"100"},
    { field: "name", headerName: "name"},
    { field: "gstname", headerName: "gstname"},
    { field: "sourceerpsystem", headerName: "sourceerpsystem"},
    { field: "business", headerName: "business"},
    { field: "soldto", headerName: "soldto"},
    { field: "customertseowner", headerName: "customertseowner"},
    { field: "caid", headerName: "caid"},
    { field: "basicuoaoverride", headerName: "basicuoaoverride"},
    { field: "accountneumonic", headerName: "accountneumonic"},
    { field: "currency", headerName: "currency"},
    { field: "frequency", headerName: "frequency"},
    { field: "validpo", headerName: "validpo"},
    { field: "porequired", headerName: "porequired"},
    { field: "status", headerName: "status"},
    { field: "contracteddate", headerName: "contracteddate"},
    { field: "enddate", headerName: "enddate"},
    { field: "bookedout", headerName: "bookedout"},
    { field: "automaticinvoicing", headerName: "automaticinvoicing"},
    { field: "notes", headerName: "notes"},
    { field: "openinvoices", headerName: "openinvoices"},
    { field: "annualsda", headerName: "annualsda"},
    { field: "offerversion", headerName: "offerversion"},
    { field: "serviceofferbandbasic", headerName: "serviceofferbandbasic"},
    { field: "serviceofferbandbasicauto", headerName: "serviceofferbandbasicauto"},
    { field: "serviceofferbandbasicvalue", headerName: "serviceofferbandbasicvalue"},
    { field: "serviceofferbandsda", headerName: "serviceofferbandsda"},
    { field: "serviceofferbandspecialist", headerName: "serviceofferbandspecialist"},
    { field: "prorata", headerName: "prorata"},
  ];

export const opt_formFields = [
  { label: "Name of the customer", value: "Name of the customer" },
//   {label:"Ownership change(changing from one customer to another)",value:"ownershipchange"},
  { label: "TSE Owner", value: "TSE Owner" },
  { label: "Currency in UOA offer", value: "Currency in UOA offer" },
  { label: "Frequency UOA Offer", value: "Frequency UOA Offer" },
];
export const opt_Marine_formFields = [
  { label: "Name of the customer", value: "Name of the customer" },
  { label: "TSE Owner", value: "TSE Owner" },
  { label: "Currency New UOA Offer", value: "Currency New UOA Offer" },
  { label: "Currency in OLD UOA offer", value: "Currency in OLD UOA offer" },
  { label: "Frequency New UOA Offer", value: "Frequency New UOA Offer" },
  { label: "Frequency OLD UOA Offer", value: "Frequency OLD UOA Offer" },
  { label: "UOA Pricing options for OLD UOA offer", value: "UOA Pricing options for OLD UOA offer" },
  { label: "UOA discount for New UOA offer", value: "UOA discount for New UOA offer" }
];
//   export const opt_formFields = [
//   { label: "Name of the customer", value: "customerName" },
//   { label: "TSE Owner", value: "tseOwner" },
//   { label: "Currency New UOA Offer", value: "currencyNew" },
//   { label: "Currency in OLD UOA offer", value: "currencyOld" },
//   { label: "Frequency New UOA Offer", value: "frequencyNew" },
//   { label: "Frequency OLD UOA Offer", value: "frequencyOld" },
//   { label: "UOA Pricing options for OLD UOA offer", value: "uoaPricingOld" },
//   { label: "UOA discount for New UOA offer", value: "uoaDiscountNew" }
// ];
  
    export const defaultRows_Cust= [
      { customerid: "2701",
        name: "SEROS SHIPPING PVT LTD",
        gstname: "",
        sourceerpsystem: "SAP",
        business: "Marine",
        soldto: "12453597",
        customertseowner: "",
        caid: "",
        basicuoaoverride: "",
        accountneumonic: "",
        currency: "USD",
        frequency: "12M",
        validpo: "n/a",
        porequired: "FALSE",
        status: "Contracted",
        contracteddate: "44530",
        enddate: "",
        bookedout: "manish.upadhyay1@bp.com",
        automaticinvoicing: "No",
        notes: "",
        openinvoices: "0",
        annualsda: "FALSE",
        offerversion: "Pre-2022",
        serviceofferbandbasic: "FALSE",
        serviceofferbandbasicauto: "FALSE",
        serviceofferbandbasicvalue: "FALSE",
        serviceofferbandsda: "",
        serviceofferbandspecialist: "",
        prorata: "TRUE"
  
      }
      // { band: "2", foc: "Bob", price: "30", currency: "$150" }
    ];

    export const opt_newaccount=[
        {label:"Yes",value:"yes"},
        {label:"No",value:"no"}
    ]

    export const opt_marine_uoaoffer=[
        {label:"Old UOA Offer",value:true},
        {label:"New UOA Offer",value:false}

    ]

    export const Discount_Matrix_columns = [
    { field: "portgroup", headerName: "Port Group" },
    { field: "group1", headerName: "Group 1 $ /HL $" },
    { field: "group2", headerName: "Group 2 $ /HL $" },
    { field: "group3", headerName: "Group 3 $ /HL $" },
    { field: "group4", headerName: "Group 4 $ /HL $" },
    { field: "group5", headerName: "Group 5 $ /HL $" },
    { field: "group6", headerName: "Group 6 $ /HL $" },
    { field: "group7", headerName: "Group 7 $ /HL $" },
    { field: "group8", headerName: "Group 8 $ /HL $" },
    { field: "group9", headerName: "Group 9 $ /HL $" },
    { field: "group10", headerName: "Group 10 $ /HL $" },
    { field: "group11", headerName: "Group 11 $ /HL $" },
    { field: "group12", headerName: "Group 12 $ /HL $" },
    { field: "group13", headerName: "Group 13 $ /HL $" }
    ];
    export const Discount_Matrix_defaultRows = [
        { portgroup: "Red Port" },
        { portgroup: "Green Port" },
        { portgroup: "White Port" }
    ];

    export const columns_discount = [
        { field: "band", headerName: "Band" },
        { field: "foc", headerName: "FOC" },
        { field: "price", headerName: "Price" },
        { field: "currency", headerName: "Currency" }
    ];

    export const defaultRows_discount = [
        { band: "1", foc: "Alice", price: "25",currency:"$125" },
        { band: "2", foc: "Alic1", price: "25",currency:"$125" },
        { band: "3", foc: "Alice", price: "25",currency:"$125" },
        { band: "4", foc: "Alice", price: "25",currency:"$125" }
    ];

    export const opt_region=[
        {value:"Europe and Africa",label:"Europe and Africa"},
        {value:"Americas",label:"Americas"},
        {value:"AsPac",label:"AsPac"},
        {value:"None - Demo",label:"None - Demo"}
    ]
    export const opt_status=[
        {value:"contracted",label:"Contracted"},
        {value:"prospect",label:"Prospect"},
        {value:"lost",label:"Lost"},
        {value:"own_change",label:"Own_change"}
    ]

    export const opt_offer_list=[
        {label:"Basic", value:"basic"},
        {label:"SDA basic (Fuel & System)", value:"sdabasic_fuel_system"},
        {label:"SDA Cylinders", value:"sdacylinders"},
        {label:"SDA Troubleshooting", value:"sdatroubleshooting"},
        {label:"Detecta (Hydraulic UOA)", value:"detecta_hydraulicuoa"},
        {label:"Specialist Stern Tube (Standard)", value:"specialiststerntube_standard"},
        {label:"Specialist Stern Tube (BV, NK)", value:"specialiststerntube_bv_nk"},
        {label:"Caremax Stern Tube with Ferrography", value:"caremaxsterntubewithferrography"},
        {label:"Predict (Machinery Condition Monitoring)", value:"predict_machineryconditionmonitoring"},
        {label:"Super", value:"super"},
        {label:"Asphaltenes", value:"asphaltenes"},
        {label:"Energy All in one", value:"Energy All in one"},
        {label:"Auto", value:"auto"},
        {label:"Basic + Asphaltenes", value:"basic_asphaltenes"}
    ]

    export const opt_offer_list_newUOA=[
        {label:"Labcheck Basic (Auto)", value:"Labcheck Basic (Auto)"},
        {label:"Labcheck Basic (Value)", value:"Labcheck Basic (Value)"},
        {label:"Labcheck Basic Condition Monitoring", value:"Labcheck Basic Condition Monitoring"},
    ]

    export const opt_offer_list_newSDA=[
        {label:"Labcheck Specialist SDA", value:"Labcheck Specialist SDA"}
    ]

    export const opt_vessel_Currency=[
        {label:"DKK", value:"DKK"},
        {label:"EUR", value:"EUR"},
        {label:"GBP", value:"GBP"},
        {label:"JPY", value:"JPY"},
        {label:"NOK", value:"NOK"},
        {label:"SEK", value:"SEK"},
        {label:"USD", value:"USD"}
    ]

    export const vesseldefaultRows = [
    {
        assetId: "14128",
        customer: "MULTITECH",
        gstName: "",
        vesselAssetName: "",
        imoNumber: "x014128",
        erpNumber: "",
        erpSystem: "JDE",
        gmeRegion: "AsPac",
        country: "Pakistan",
        salesRegion: "AsPac",
        salesCountry: "Pakistan",
        vesselAssetTseOwner: "",
        customerTseOwner: "",
        business: "Energy",
        validPo: "No",
        startDate: "2021-05-20",
        endDate: "",
        currency: "USD",
        frequency: "3M",
        status: "Contracted",
        bookedOut: "",
        automaticInvoicing: "No, Inherited",
        notes: ""
    },
    {
        assetId: "15946",
        customer: "MULTITECH",
        gstName: "",
        vesselAssetName: "",
        imoNumber: "x015946",
        erpNumber: "",
        erpSystem: "JDE",
        gmeRegion: "AsPac",
        country: "Pakistan",
        salesRegion: "AsPac",
        salesCountry: "Pakistan",
        vesselAssetTseOwner: "",
        customerTseOwner: "",
        business: "Energy",
        validPo: "No",
        startDate: "2021-01-01",
        endDate: "",
        currency: "USD",
        frequency: "3M",
        status: "Contracted",
        bookedOut: "",
        automaticInvoicing: "Yes",
        notes: ""
    },
    {
        assetId: "16434",
        customer: "MULTITECH",
        gstName: "",
        vesselAssetName: "",
        imoNumber: "x016434",
        erpNumber: "",
        erpSystem: "JDE",
        gmeRegion: "AsPac",
        country: "Pakistan",
        salesRegion: "AsPac",
        salesCountry: "Pakistan",
        vesselAssetTseOwner: "",
        customerTseOwner: "",
        business: "Energy",
        validPo: "No",
        startDate: "2021-12-05",
        endDate: "",
        currency: "USD",
        frequency: "3M",
        status: "Contracted",
        bookedOut: "",
        automaticInvoicing: "No",
        notes: ""
    }
    ];

    export const opt_test_suite=[
  
    ]
    export const opt_tse = [
        { label: "Alejandro.Baeza-Gonzalez@uk.bp.com",        value: "Alejandro.Baeza-Gonzalez@uk.bp.com"        },
        { label: "Are.Sletten@ec1.bp.com",                    value: "Are.Sletten@ec1.bp.com"                    },
        { label: "balaji.srinivasan@bp.com",                  value: "balaji.srinivasan@bp.com"                  },
        { label: "Barry.Sullivan@uk.bp.com",                  value: "Barry.Sullivan@uk.bp.com"                  },
        { label: "Bevis.Chew@bp.com",                         value: "Bevis.Chew@bp.com"                         },
        { label: "Bin.Hou@se1.bp.com",                        value: "Bin.Hou@se1.bp.com"                        },
        { label: "Chad.Heins@bp.com",                         value: "Chad.Heins@bp.com"                         },
        { label: "charles.applewhite@bp.com",                 value: "charles.applewhite@bp.com"                 },
        { label: "Charles.Swift@uk.bp.com",                   value: "Charles.Swift@uk.bp.com"                   },
        { label: "Charles.Wang@bp.com",                       value: "Charles.Wang@bp.com"                       },
        { label: "Chris.Morrissey@castrol.com",               value: "Chris.Morrissey@castrol.com"               },
        { label: "chuyan.nah@bp.com",                         value: "chuyan.nah@bp.com"                         },
        { label: "Ciaran.Jefferies@uk.bp.com",                value: "Ciaran.Jefferies@uk.bp.com"                },
        { label: "daniele.castrucci@ec1.bp.com",              value: "daniele.castrucci@ec1.bp.com"              },
        { label: "David.Vieira@leopardhq.com",                value: "David.Vieira@leopardhq.com"                },
        { label: "Dimitris.Katsieris@ec1.bp.com",             value: "Dimitris.Katsieris@ec1.bp.com"             },
        { label: "Dirk.Lorentzen@de.bp.com",                  value: "Dirk.Lorentzen@de.bp.com"                  },
        { label: "diwakar.kumar1@bp.com",                     value: "diwakar.kumar1@bp.com"                     },
        { label: "Dominiek.Cracco@castrol.com",               value: "Dominiek.Cracco@castrol.com"               },
        { label: "Eleftheria.Katsikavella@ec1.bp.com",        value: "Eleftheria.Katsikavella@ec1.bp.com"        },
        { label: "Eleni.Peppa@bp.com",                        value: "Eleni.Peppa@bp.com"                        },
        { label: "ellen.sorgard@bp.com",                      value: "ellen.sorgard@bp.com"                      },
        { label: "enrique.callejotorre@ec1.bp.com",           value: "enrique.callejotorre@ec1.bp.com"           },
        { label: "felix.bullik@bp.com",                       value: "felix.bullik@bp.com"                       },
        { label: "frank.li@se1.bp.com",                       value: "frank.li@se1.bp.com"                       },
        { label: "Gabriel.Remolina1@bp.com",                  value: "Gabriel.Remolina1@bp.com"                  },
        { label: "George.Athanasopoulos@ec1.bp.com",          value: "George.Athanasopoulos@ec1.bp.com"          },
        { label: "Georgios.Leontarakis@ec1.bp.com",           value: "Georgios.Leontarakis@ec1.bp.com"           },
        { label: "glubesgsthelp@bp.com",                      value: "glubesgsthelp@bp.com"                      },
        { label: "Grigoris.Sioris@bp.com",                    value: "Grigoris.Sioris@bp.com"                    },
        { label: "harsimran_kaur_kler.lakbir_singh@bp.com",   value: "harsimran_kaur_kler.lakbir_singh@bp.com"   },
        { label: "howard.silver@uk.bp.com",                   value: "howard.silver@uk.bp.com"                   },
        { label: "jack.cheek@bp.com",                         value: "jack.cheek@bp.com"                         },
        { label: "Jake.Keel@bp.com",                          value: "Jake.Keel@bp.com"                          },
        { label: "James.Ford2@uk.bp.com",                     value: "James.Ford2@uk.bp.com"                     },
        { label: "James.Torrance@uk.bp.com",                  value: "James.Torrance@uk.bp.com"                  },
        { label: "jamestorrance1989@gmail.com",               value: "jamestorrance1989@gmail.com"               },
        { label: "Jie.Li@bp.com",                             value: "Jie.Li@bp.com"                             },
        { label: "jinhao.chang@bp.com",                       value: "jinhao.chang@bp.com"                       },
        { label: "jiyoung.hong@bp.com",                       value: "jiyoung.hong@bp.com"                       },
        { label: "joel.ong@se1.bp.com",                       value: "joel.ong@se1.bp.com"                       },
        { label: "jolynn.puah@se1.bp.com",                    value: "jolynn.puah@se1.bp.com"                    },
        { label: "Jose.Benitez@bp.com",                       value: "Jose.Benitez@bp.com"                       },
        { label: "karchai.tan@bp.com",                        value: "karchai.tan@bp.com"                        },
        { label: "ken.on@se1.bp.com",                         value: "ken.on@se1.bp.com"                         },
        { label: "klaas.kramer@bp.com",                       value: "klaas.kramer@bp.com"                       },
        { label: "kushi.s@bp.com",                            value: "kushi.s@bp.com"                            },
        { label: "Lene.Carlsson@ec1.bp.com",                  value: "Lene.Carlsson@ec1.bp.com"                  },
        { label: "Leon.Jones@uk.bp.com",                      value: "Leon.Jones@uk.bp.com"                      },
        { label: "liua@castrol.com",                          value: "liua@castrol.com"                          },
        { label: "manigandan.t@bp.com",                       value: "manigandan.t@bp.com"                       },
        { label: "martin.kuhnel@bp.com",                      value: "martin.kuhnel@bp.com"                      },
        { label: "maruthi.varre@bp.com",                      value: "maruthi.varre@bp.com"                      },
        { label: "Michael.Nowak@de.bp.com",                   value: "Michael.Nowak@de.bp.com"                   },
        { label: "Mike.DeVore@Castrol.com",                   value: "Mike.DeVore@Castrol.com"                   },
        { label: "Min.Kim1@bp.com",                           value: "Min.Kim1@bp.com"                           },
        { label: "ming_sheng.kang@se1.bp.com",                value: "ming_sheng.kang@se1.bp.com"                },
        { label: "morten.tambo@castrol.com",                  value: "morten.tambo@castrol.com"                  },
        { label: "nagaraju.yarakula@bp.com",                  value: "nagaraju.yarakula@bp.com"                  },
        { label: "Nicky.Plumb@uk.bp.com",                     value: "Nicky.Plumb@uk.bp.com"                     },
        { label: "nikhil.bansal1@bp.com",                     value: "nikhil.bansal1@bp.com"                     },
        { label: "Niroshan.Niriella@uk.bp.com",               value: "Niroshan.Niriella@uk.bp.com"               },
        { label: "NoEmail - Jon Pearce",                      value: "NoEmail - Jon Pearce"                      },
        { label: "NoEmail - Orxan Yuzbashi",                  value: "NoEmail - Orxan Yuzbashi"                  },
        { label: "NoEmail - Test User",                       value: "NoEmail - Test User"                       },
        { label: "NoEmail - Vugar Abdullayev",                value: "NoEmail - Vugar Abdullayev"                },
        { label: "oeyvind.hansen@castrol.com",                value: "oeyvind.hansen@castrol.com"                },
        { label: "Oliver.Ferguson@bp.com",                    value: "Oliver.Ferguson@bp.com"                    },
        { label: "Oluwafemi.Kesington@bp.com",                value: "Oluwafemi.Kesington@bp.com"                },
        { label: "patrick.kwok@se1.bp.com",                   value: "patrick.kwok@se1.bp.com"                   },
        { label: "Paul.Fairweather@uk.bp.com",                value: "Paul.Fairweather@uk.bp.com"                },
        { label: "prasanna.bari@bp.com",                      value: "prasanna.bari@bp.com"                      },
        { label: "Richard.Leahy@uk.bp.com",                   value: "Richard.Leahy@uk.bp.com"                   },
        { label: "rob.willemsteijn@ec1.bp.com",               value: "rob.willemsteijn@ec1.bp.com"               },
        { label: "Sam.Johns@se1.bp.com",                      value: "Sam.Johns@se1.bp.com"                      },
        { label: "SAMUEL.WALKER@bp.com",                      value: "SAMUEL.WALKER@bp.com"                      },
        { label: "Saurabh.Pal@me1.bp.com",                    value: "Saurabh.Pal@me1.bp.com"                    },
        { label: "Sean.Komatinsky@castrol.com",               value: "Sean.Komatinsky@castrol.com"               },
        { label: "seiya.ohkawa@se1.bp.com",                   value: "seiya.ohkawa@se1.bp.com"                   },
        { label: "shoin.tanaka@se1.bp.com",                   value: "shoin.tanaka@se1.bp.com"                   },
        { label: "Simon.Youngman@castrol.com",                value: "Simon.Youngman@castrol.com"                },
        { label: "sonny.moller@castrol.com",                  value: "sonny.moller@castrol.com"                  },
        { label: "sravani.yasarapu@bp.com",                   value: "sravani.yasarapu@bp.com"                   },
        { label: "steef.poolman@bp.com",                      value: "steef.poolman@bp.com"                      },
        { label: "Thomas.Reynolds@bp.com",                    value: "Thomas.Reynolds@bp.com"                    },
        { label: "tony.globe@castrol.com",                    value: "tony.globe@castrol.com"                    },
        { label: "vadde.ganesh@bp.com",                       value: "vadde.ganesh@bp.com"                       },
        { label: "venkatesh.kanale@bp.com",                   value: "venkatesh.kanale@bp.com"                   },
        { label: "vikram.srivastava@se1.bp.com",              value: "vikram.srivastava@se1.bp.com"              },
        { label: "wei.zhou2@se1.bp.com",                      value: "wei.zhou2@se1.bp.com"                      },
        { label: "xin.tan@bp.com",                            value: "xin.tan@bp.com"                            },
        { label: "yudha_rahman.awallu@bp.com",                value: "yudha_rahman.awallu@bp.com"                },
        { label: "yukihiro.masubuchi@se1.bp.com",             value: "yukihiro.masubuchi@se1.bp.com"             },
        { label: "zhangyu.xu@bp.com",                         value: "zhangyu.xu@bp.com"                         },
      ];